export const US_CITIES: { city: string; state: string }[] = [
  // Alabama
  { city: "Birmingham", state: "AL" },
  { city: "Montgomery", state: "AL" },
  { city: "Huntsville", state: "AL" },
  { city: "Mobile", state: "AL" },
  { city: "Tuscaloosa", state: "AL" },
  { city: "Hoover", state: "AL" },
  { city: "Dothan", state: "AL" },
  { city: "Auburn", state: "AL" },
  { city: "Decatur", state: "AL" },
  { city: "Madison", state: "AL" },
  { city: "Florence", state: "AL" },
  { city: "Gadsden", state: "AL" },
  { city: "Vestavia Hills", state: "AL" },
  { city: "Prattville", state: "AL" },
  { city: "Phenix City", state: "AL" },
  { city: "Alabaster", state: "AL" },
  { city: "Bessemer", state: "AL" },
  { city: "Enterprise", state: "AL" },
  { city: "Opelika", state: "AL" },
  { city: "Homewood", state: "AL" },
  // Alaska
  { city: "Anchorage", state: "AK" },
  { city: "Fairbanks", state: "AK" },
  { city: "Juneau", state: "AK" },
  { city: "Sitka", state: "AK" },
  { city: "Ketchikan", state: "AK" },
  { city: "Wasilla", state: "AK" },
  { city: "Kenai", state: "AK" },
  { city: "Kodiak", state: "AK" },
  // Arizona
  { city: "Phoenix", state: "AZ" },
  { city: "Tucson", state: "AZ" },
  { city: "Mesa", state: "AZ" },
  { city: "Chandler", state: "AZ" },
  { city: "Scottsdale", state: "AZ" },
  { city: "Gilbert", state: "AZ" },
  { city: "Tempe", state: "AZ" },
  { city: "Glendale", state: "AZ" },
  { city: "Peoria", state: "AZ" },
  { city: "Surprise", state: "AZ" },
  { city: "Yuma", state: "AZ" },
  { city: "Avondale", state: "AZ" },
  { city: "Goodyear", state: "AZ" },
  { city: "Flagstaff", state: "AZ" },
  { city: "Sedona", state: "AZ" },
  { city: "Lake Havasu City", state: "AZ" },
  { city: "Prescott", state: "AZ" },
  { city: "Casa Grande", state: "AZ" },
  { city: "Maricopa", state: "AZ" },
  { city: "Queen Creek", state: "AZ" },
  { city: "Buckeye", state: "AZ" },
  { city: "Oro Valley", state: "AZ" },
  { city: "Marana", state: "AZ" },
  { city: "Fountain Hills", state: "AZ" },
  { city: "Paradise Valley", state: "AZ" },
  { city: "Litchfield Park", state: "AZ" },
  // Arkansas
  { city: "Little Rock", state: "AR" },
  { city: "Fort Smith", state: "AR" },
  { city: "Fayetteville", state: "AR" },
  { city: "Springdale", state: "AR" },
  { city: "Jonesboro", state: "AR" },
  { city: "North Little Rock", state: "AR" },
  { city: "Conway", state: "AR" },
  { city: "Rogers", state: "AR" },
  { city: "Bentonville", state: "AR" },
  { city: "Pine Bluff", state: "AR" },
  { city: "Bella Vista", state: "AR" },
  { city: "Hot Springs", state: "AR" },
  { city: "Texarkana", state: "AR" },
  // California
  { city: "Los Angeles", state: "CA" },
  { city: "San Diego", state: "CA" },
  { city: "San Jose", state: "CA" },
  { city: "San Francisco", state: "CA" },
  { city: "Fresno", state: "CA" },
  { city: "Sacramento", state: "CA" },
  { city: "Long Beach", state: "CA" },
  { city: "Oakland", state: "CA" },
  { city: "Bakersfield", state: "CA" },
  { city: "Anaheim", state: "CA" },
  { city: "Santa Ana", state: "CA" },
  { city: "Riverside", state: "CA" },
  { city: "Stockton", state: "CA" },
  { city: "Irvine", state: "CA" },
  { city: "Chula Vista", state: "CA" },
  { city: "Fremont", state: "CA" },
  { city: "San Bernardino", state: "CA" },
  { city: "Modesto", state: "CA" },
  { city: "Fontana", state: "CA" },
  { city: "Moreno Valley", state: "CA" },
  { city: "Glendale", state: "CA" },
  { city: "Huntington Beach", state: "CA" },
  { city: "Santa Clarita", state: "CA" },
  { city: "Garden Grove", state: "CA" },
  { city: "Oceanside", state: "CA" },
  { city: "Rancho Cucamonga", state: "CA" },
  { city: "Santa Rosa", state: "CA" },
  { city: "Ontario", state: "CA" },
  { city: "Corona", state: "CA" },
  { city: "Elk Grove", state: "CA" },
  { city: "Lancaster", state: "CA" },
  { city: "Palmdale", state: "CA" },
  { city: "Salinas", state: "CA" },
  { city: "Pomona", state: "CA" },
  { city: "Torrance", state: "CA" },
  { city: "Escondido", state: "CA" },
  { city: "Sunnyvale", state: "CA" },
  { city: "Pasadena", state: "CA" },
  { city: "Orange", state: "CA" },
  { city: "Fullerton", state: "CA" },
  { city: "Hayward", state: "CA" },
  { city: "Visalia", state: "CA" },
  { city: "Concord", state: "CA" },
  { city: "Roseville", state: "CA" },
  { city: "Santa Clara", state: "CA" },
  { city: "Thousand Oaks", state: "CA" },
  { city: "Simi Valley", state: "CA" },
  { city: "Vallejo", state: "CA" },
  { city: "Victorville", state: "CA" },
  { city: "El Monte", state: "CA" },
  { city: "Berkeley", state: "CA" },
  { city: "Downey", state: "CA" },
  { city: "Costa Mesa", state: "CA" },
  { city: "Inglewood", state: "CA" },
  { city: "Ventura", state: "CA" },
  { city: "West Covina", state: "CA" },
  { city: "Norwalk", state: "CA" },
  { city: "Burbank", state: "CA" },
  { city: "Antioch", state: "CA" },
  { city: "Santa Monica", state: "CA" },
  { city: "Beverly Hills", state: "CA" },
  { city: "Malibu", state: "CA" },
  { city: "Palm Springs", state: "CA" },
  { city: "Newport Beach", state: "CA" },
  { city: "Laguna Beach", state: "CA" },
  { city: "Laguna Niguel", state: "CA" },
  { city: "Laguna Hills", state: "CA" },
  { city: "Mission Viejo", state: "CA" },
  { city: "Lake Forest", state: "CA" },
  { city: "Aliso Viejo", state: "CA" },
  { city: "San Clemente", state: "CA" },
  { city: "Dana Point", state: "CA" },
  { city: "San Luis Obispo", state: "CA" },
  { city: "Santa Barbara", state: "CA" },
  { city: "Napa", state: "CA" },
  { city: "Palo Alto", state: "CA" },
  { city: "Mountain View", state: "CA" },
  { city: "Redwood City", state: "CA" },
  { city: "San Mateo", state: "CA" },
  { city: "Daly City", state: "CA" },
  { city: "South San Francisco", state: "CA" },
  { city: "San Leandro", state: "CA" },
  { city: "Richmond", state: "CA" },
  { city: "Petaluma", state: "CA" },
  { city: "Hollywood", state: "CA" },
  { city: "West Hollywood", state: "CA" },
  { city: "Studio City", state: "CA" },
  { city: "Sherman Oaks", state: "CA" },
  { city: "Encino", state: "CA" },
  { city: "Woodland Hills", state: "CA" },
  { city: "Tarzana", state: "CA" },
  { city: "Van Nuys", state: "CA" },
  { city: "North Hollywood", state: "CA" },
  { city: "Reseda", state: "CA" },
  { city: "Canoga Park", state: "CA" },
  { city: "Chatsworth", state: "CA" },
  { city: "Northridge", state: "CA" },
  { city: "Granada Hills", state: "CA" },
  { city: "Mission Hills", state: "CA" },
  { city: "Sylmar", state: "CA" },
  { city: "Sun Valley", state: "CA" },
  { city: "Pacoima", state: "CA" },
  { city: "Arleta", state: "CA" },
  { city: "Panorama City", state: "CA" },
  { city: "Marina Del Rey", state: "CA" },
  { city: "Venice", state: "CA" },
  { city: "Culver City", state: "CA" },
  { city: "El Segundo", state: "CA" },
  { city: "Manhattan Beach", state: "CA" },
  { city: "Hermosa Beach", state: "CA" },
  { city: "Redondo Beach", state: "CA" },
  { city: "Palos Verdes", state: "CA" },
  { city: "Rancho Palos Verdes", state: "CA" },
  { city: "San Pedro", state: "CA" },
  { city: "Oxnard", state: "CA" },
  { city: "Camarillo", state: "CA" },
  { city: "Moorpark", state: "CA" },
  { city: "Newbury Park", state: "CA" },
  { city: "Agoura Hills", state: "CA" },
  { city: "Calabasas", state: "CA" },
  { city: "Westlake Village", state: "CA" },
  { city: "Fillmore", state: "CA" },
  { city: "Santa Paula", state: "CA" },
  { city: "Lompoc", state: "CA" },
  { city: "Santa Maria", state: "CA" },
  { city: "Goleta", state: "CA" },
  { city: "Carpinteria", state: "CA" },
  { city: "Montecito", state: "CA" },
  { city: "Paso Robles", state: "CA" },
  { city: "Arroyo Grande", state: "CA" },
  { city: "Pismo Beach", state: "CA" },
  { city: "Morro Bay", state: "CA" },
  { city: "Atascadero", state: "CA" },
  { city: "Templeton", state: "CA" },
  { city: "Monterey", state: "CA" },
  { city: "Carmel", state: "CA" },
  { city: "Carmel-by-the-Sea", state: "CA" },
  { city: "Pacific Grove", state: "CA" },
  { city: "Seaside", state: "CA" },
  { city: "Marina", state: "CA" },
  { city: "Watsonville", state: "CA" },
  { city: "Santa Cruz", state: "CA" },
  { city: "Capitola", state: "CA" },
  { city: "Aptos", state: "CA" },
  { city: "Half Moon Bay", state: "CA" },
  { city: "San Rafael", state: "CA" },
  { city: "Novato", state: "CA" },
  { city: "Mill Valley", state: "CA" },
  { city: "Sausalito", state: "CA" },
  { city: "Tiburon", state: "CA" },
  { city: "Fairfax", state: "CA" },
  { city: "San Anselmo", state: "CA" },
  { city: "Corte Madera", state: "CA" },
  { city: "Larkspur", state: "CA" },
  { city: "San Ramon", state: "CA" },
  { city: "Walnut Creek", state: "CA" },
  { city: "Pleasant Hill", state: "CA" },
  { city: "Lafayette", state: "CA" },
  { city: "Orinda", state: "CA" },
  { city: "Moraga", state: "CA" },
  { city: "Danville", state: "CA" },
  { city: "Alamo", state: "CA" },
  { city: "Dublin", state: "CA" },
  { city: "Pleasanton", state: "CA" },
  { city: "Livermore", state: "CA" },
  { city: "Union City", state: "CA" },
  { city: "Newark", state: "CA" },
  { city: "Milpitas", state: "CA" },
  { city: "Santa Teresa", state: "CA" },
  { city: "Cupertino", state: "CA" },
  { city: "Los Gatos", state: "CA" },
  { city: "Los Altos", state: "CA" },
  { city: "Saratoga", state: "CA" },
  { city: "Campbell", state: "CA" },
  { city: "San Marcos", state: "CA" },
  { city: "Carlsbad", state: "CA" },
  { city: "Encinitas", state: "CA" },
  { city: "Solana Beach", state: "CA" },
  { city: "Del Mar", state: "CA" },
  { city: "La Jolla", state: "CA" },
  { city: "Chula Vista", state: "CA" },
  { city: "National City", state: "CA" },
  { city: "El Cajon", state: "CA" },
  { city: "La Mesa", state: "CA" },
  { city: "Lemon Grove", state: "CA" },
  { city: "Santee", state: "CA" },
  { city: "Poway", state: "CA" },
  { city: "Rancho Santa Fe", state: "CA" },
  { city: "Vista", state: "CA" },
  { city: "San Marcos", state: "CA" },
  { city: "Fallbrook", state: "CA" },
  { city: "Temecula", state: "CA" },
  { city: "Murrieta", state: "CA" },
  { city: "Menifee", state: "CA" },
  { city: "Hemet", state: "CA" },
  { city: "Perris", state: "CA" },
  { city: "Lake Elsinore", state: "CA" },
  { city: "Canyon Lake", state: "CA" },
  { city: "Palm Desert", state: "CA" },
  { city: "La Quinta", state: "CA" },
  { city: "Indian Wells", state: "CA" },
  { city: "Cathedral City", state: "CA" },
  { city: "Desert Hot Springs", state: "CA" },
  { city: "Coachella", state: "CA" },
  { city: "Indio", state: "CA" },
  { city: "Rancho Mirage", state: "CA" },
  { city: "Rialto", state: "CA" },
  { city: "Colton", state: "CA" },
  { city: "Redlands", state: "CA" },
  { city: "Yucaipa", state: "CA" },
  { city: "Loma Linda", state: "CA" },
  { city: "Upland", state: "CA" },
  { city: "Claremont", state: "CA" },
  { city: "Montclair", state: "CA" },
  { city: "Chino", state: "CA" },
  { city: "Chino Hills", state: "CA" },
  { city: "Diamond Bar", state: "CA" },
  { city: "Walnut", state: "CA" },
  { city: "Rowland Heights", state: "CA" },
  { city: "La Puente", state: "CA" },
  { city: "Baldwin Park", state: "CA" },
  { city: "Covina", state: "CA" },
  { city: "Azusa", state: "CA" },
  { city: "Glendora", state: "CA" },
  { city: "San Dimas", state: "CA" },
  { city: "La Verne", state: "CA" },
  { city: "Monrovia", state: "CA" },
  { city: "Arcadia", state: "CA" },
  { city: "Temple City", state: "CA" },
  { city: "San Gabriel", state: "CA" },
  { city: "Alhambra", state: "CA" },
  { city: "Monterey Park", state: "CA" },
  { city: "Rosemead", state: "CA" },
  { city: "Commerce", state: "CA" },
  { city: "Bell Gardens", state: "CA" },
  { city: "Paramount", state: "CA" },
  { city: "Bellflower", state: "CA" },
  { city: "Cerritos", state: "CA" },
  { city: "Lakewood", state: "CA" },
  { city: "Compton", state: "CA" },
  { city: "Hawthorne", state: "CA" },
  { city: "Gardena", state: "CA" },
  { city: "Carson", state: "CA" },
  { city: "Whittier", state: "CA" },
  { city: "Pico Rivera", state: "CA" },
  { city: "Montebello", state: "CA" },
  // Colorado
  { city: "Denver", state: "CO" },
  { city: "Colorado Springs", state: "CO" },
  { city: "Aurora", state: "CO" },
  { city: "Fort Collins", state: "CO" },
  { city: "Lakewood", state: "CO" },
  { city: "Thornton", state: "CO" },
  { city: "Arvada", state: "CO" },
  { city: "Westminster", state: "CO" },
  { city: "Pueblo", state: "CO" },
  { city: "Boulder", state: "CO" },
  { city: "Aspen", state: "CO" },
  { city: "Vail", state: "CO" },
  { city: "Breckenridge", state: "CO" },
  { city: "Steamboat Springs", state: "CO" },
  { city: "Telluride", state: "CO" },
  { city: "Durango", state: "CO" },
  { city: "Grand Junction", state: "CO" },
  { city: "Loveland", state: "CO" },
  { city: "Greeley", state: "CO" },
  { city: "Longmont", state: "CO" },
  { city: "Broomfield", state: "CO" },
  { city: "Centennial", state: "CO" },
  { city: "Highlands Ranch", state: "CO" },
  { city: "Parker", state: "CO" },
  { city: "Castle Rock", state: "CO" },
  { city: "Littleton", state: "CO" },
  { city: "Englewood", state: "CO" },
  { city: "Glenwood Springs", state: "CO" },
  { city: "Montrose", state: "CO" },
  { city: "Pueblo West", state: "CO" },
  // Connecticut
  { city: "Bridgeport", state: "CT" },
  { city: "New Haven", state: "CT" },
  { city: "Stamford", state: "CT" },
  { city: "Hartford", state: "CT" },
  { city: "Waterbury", state: "CT" },
  { city: "Greenwich", state: "CT" },
  { city: "Norwalk", state: "CT" },
  { city: "Danbury", state: "CT" },
  { city: "New Britain", state: "CT" },
  { city: "West Hartford", state: "CT" },
  { city: "Glastonbury", state: "CT" },
  { city: "Milford", state: "CT" },
  { city: "Fairfield", state: "CT" },
  { city: "Westport", state: "CT" },
  { city: "Darien", state: "CT" },
  { city: "New Canaan", state: "CT" },
  { city: "Wilton", state: "CT" },
  { city: "Ridgefield", state: "CT" },
  { city: "Trumbull", state: "CT" },
  { city: "Shelton", state: "CT" },
  { city: "Stratford", state: "CT" },
  { city: "New Milford", state: "CT" },
  { city: "Newtown", state: "CT" },
  { city: "Hamden", state: "CT" },
  { city: "Meriden", state: "CT" },
  { city: "Middletown", state: "CT" },
  { city: "Bristol", state: "CT" },
  // Delaware
  { city: "Wilmington", state: "DE" },
  { city: "Dover", state: "DE" },
  { city: "Newark", state: "DE" },
  { city: "Middletown", state: "DE" },
  { city: "Bear", state: "DE" },
  { city: "Smyrna", state: "DE" },
  { city: "Milford", state: "DE" },
  { city: "Rehoboth Beach", state: "DE" },
  { city: "Lewes", state: "DE" },
  // Washington DC
  { city: "Washington", state: "DC" },
  // Florida
  { city: "Jacksonville", state: "FL" },
  { city: "Miami", state: "FL" },
  { city: "Tampa", state: "FL" },
  { city: "Orlando", state: "FL" },
  { city: "St. Petersburg", state: "FL" },
  { city: "Hialeah", state: "FL" },
  { city: "Port St. Lucie", state: "FL" },
  { city: "Cape Coral", state: "FL" },
  { city: "Tallahassee", state: "FL" },
  { city: "Fort Lauderdale", state: "FL" },
  { city: "Pembroke Pines", state: "FL" },
  { city: "Hollywood", state: "FL" },
  { city: "Miramar", state: "FL" },
  { city: "Gainesville", state: "FL" },
  { city: "Coral Springs", state: "FL" },
  { city: "Miami Gardens", state: "FL" },
  { city: "Clearwater", state: "FL" },
  { city: "Palm Bay", state: "FL" },
  { city: "Pompano Beach", state: "FL" },
  { city: "West Palm Beach", state: "FL" },
  { city: "Lakeland", state: "FL" },
  { city: "Davie", state: "FL" },
  { city: "Miami Beach", state: "FL" },
  { city: "Sunrise", state: "FL" },
  { city: "Plantation", state: "FL" },
  { city: "Boca Raton", state: "FL" },
  { city: "Deltona", state: "FL" },
  { city: "Largo", state: "FL" },
  { city: "Deerfield Beach", state: "FL" },
  { city: "Palm Coast", state: "FL" },
  { city: "Melbourne", state: "FL" },
  { city: "Boynton Beach", state: "FL" },
  { city: "Lauderhill", state: "FL" },
  { city: "Fort Myers", state: "FL" },
  { city: "Sarasota", state: "FL" },
  { city: "Daytona Beach", state: "FL" },
  { city: "Naples", state: "FL" },
  { city: "Key West", state: "FL" },
  { city: "Kissimmee", state: "FL" },
  { city: "Sanford", state: "FL" },
  { city: "Ocala", state: "FL" },
  { city: "Pensacola", state: "FL" },
  { city: "Aventura", state: "FL" },
  { city: "Doral", state: "FL" },
  { city: "Coral Gables", state: "FL" },
  { city: "Hallandale Beach", state: "FL" },
  { city: "Homestead", state: "FL" },
  { city: "Delray Beach", state: "FL" },
  { city: "Lake Worth", state: "FL" },
  { city: "Margate", state: "FL" },
  { city: "Coconut Creek", state: "FL" },
  { city: "North Miami", state: "FL" },
  { city: "Weston", state: "FL" },
  { city: "Tamarac", state: "FL" },
  { city: "St. Augustine", state: "FL" },
  { city: "Bradenton", state: "FL" },
  { city: "Palm Beach", state: "FL" },
  { city: "Palm Beach Gardens", state: "FL" },
  { city: "Jupiter", state: "FL" },
  { city: "Stuart", state: "FL" },
  { city: "Vero Beach", state: "FL" },
  { city: "Fort Pierce", state: "FL" },
  { city: "Sebastian", state: "FL" },
  { city: "Melbourne Beach", state: "FL" },
  { city: "Cocoa Beach", state: "FL" },
  { city: "Titusville", state: "FL" },
  { city: "New Smyrna Beach", state: "FL" },
  { city: "Ormond Beach", state: "FL" },
  { city: "Palm Coast", state: "FL" },
  { city: "Ponte Vedra Beach", state: "FL" },
  { city: "Fernandina Beach", state: "FL" },
  { city: "Amelia Island", state: "FL" },
  { city: "Destin", state: "FL" },
  { city: "Fort Walton Beach", state: "FL" },
  { city: "Panama City Beach", state: "FL" },
  { city: "Panama City", state: "FL" },
  { city: "Tallahassee", state: "FL" },
  { city: "Gainesville", state: "FL" },
  { city: "Ocala", state: "FL" },
  { city: "The Villages", state: "FL" },
  { city: "Leesburg", state: "FL" },
  { city: "Clermont", state: "FL" },
  { city: "Winter Garden", state: "FL" },
  { city: "Ocoee", state: "FL" },
  { city: "Winter Park", state: "FL" },
  { city: "Altamonte Springs", state: "FL" },
  { city: "Casselberry", state: "FL" },
  { city: "Oviedo", state: "FL" },
  { city: "Lake Mary", state: "FL" },
  { city: "Longwood", state: "FL" },
  { city: "Apopka", state: "FL" },
  { city: "Daytona Beach", state: "FL" },
  { city: "Port Orange", state: "FL" },
  { city: "Holly Hill", state: "FL" },
  { city: "South Daytona", state: "FL" },
  { city: "Edgewater", state: "FL" },
  { city: "South Beach", state: "FL" },
  { city: "Miami Lakes", state: "FL" },
  { city: "Miami Shores", state: "FL" },
  { city: "Sunny Isles Beach", state: "FL" },
  { city: "Bal Harbour", state: "FL" },
  { city: "Bay Harbor Islands", state: "FL" },
  { city: "Surfside", state: "FL" },
  { city: "North Miami Beach", state: "FL" },
  { city: "Opa-locka", state: "FL" },
  { city: "Hialeah Gardens", state: "FL" },
  { city: "Medley", state: "FL" },
  { city: "Key Biscayne", state: "FL" },
  { city: "Brickell", state: "FL" },
  { city: "Wynwood", state: "FL" },
  { city: "Little Havana", state: "FL" },
  { city: "Coconut Grove", state: "FL" },
  { city: "Cutler Bay", state: "FL" },
  { city: "Pinecrest", state: "FL" },
  { city: "South Miami", state: "FL" },
  { city: "Westchester", state: "FL" },
  { city: "Kendale Lakes", state: "FL" },
  { city: "Kendall", state: "FL" },
  { city: "Palmetto Bay", state: "FL" },
  { city: "Naranja", state: "FL" },
  { city: "Perrine", state: "FL" },
  { city: "Goulds", state: "FL" },
  { city: "Florida City", state: "FL" },
  { city: "Islamorada", state: "FL" },
  { city: "Marathon", state: "FL" },
  { city: "Big Pine Key", state: "FL" },
  { city: "Key Largo", state: "FL" },
  { city: "Cape Coral", state: "FL" },
  { city: "Bonita Springs", state: "FL" },
  { city: "Estero", state: "FL" },
  { city: "Marco Island", state: "FL" },
  { city: "Immokalee", state: "FL" },
  { city: "Lehigh Acres", state: "FL" },
  { city: "Port Charlotte", state: "FL" },
  { city: "Punta Gorda", state: "FL" },
  { city: "North Port", state: "FL" },
  { city: "Venice", state: "FL" },
  { city: "Englewood", state: "FL" },
  { city: "Osprey", state: "FL" },
  { city: "Nokomis", state: "FL" },
  { city: "Siesta Key", state: "FL" },
  { city: "Longboat Key", state: "FL" },
  { city: "Anna Maria", state: "FL" },
  { city: "Holmes Beach", state: "FL" },
  { city: "Palmetto", state: "FL" },
  { city: "Ellenton", state: "FL" },
  { city: "Parrish", state: "FL" },
  { city: "Ruskin", state: "FL" },
  { city: "Sun City Center", state: "FL" },
  { city: "Apollo Beach", state: "FL" },
  { city: "Riverview", state: "FL" },
  { city: "Brandon", state: "FL" },
  { city: "Seffner", state: "FL" },
  { city: "Plant City", state: "FL" },
  { city: "Valrico", state: "FL" },
  { city: "Wesley Chapel", state: "FL" },
  { city: "New Tampa", state: "FL" },
  { city: "Land O Lakes", state: "FL" },
  { city: "Lutz", state: "FL" },
  { city: "Odessa", state: "FL" },
  { city: "Dunedin", state: "FL" },
  { city: "Safety Harbor", state: "FL" },
  { city: "Oldsmar", state: "FL" },
  { city: "Palm Harbor", state: "FL" },
  { city: "Tarpon Springs", state: "FL" },
  { city: "New Port Richey", state: "FL" },
  { city: "Holiday", state: "FL" },
  { city: "Hudson", state: "FL" },
  { city: "Spring Hill", state: "FL" },
  { city: "Brooksville", state: "FL" },
  // Georgia
  { city: "Atlanta", state: "GA" },
  { city: "Columbus", state: "GA" },
  { city: "Augusta", state: "GA" },
  { city: "Macon", state: "GA" },
  { city: "Savannah", state: "GA" },
  { city: "Athens", state: "GA" },
  { city: "Sandy Springs", state: "GA" },
  { city: "Roswell", state: "GA" },
  { city: "Alpharetta", state: "GA" },
  { city: "Marietta", state: "GA" },
  { city: "Brookhaven", state: "GA" },
  { city: "Dunwoody", state: "GA" },
  { city: "Smyrna", state: "GA" },
  { city: "Johns Creek", state: "GA" },
  { city: "Warner Robins", state: "GA" },
  { city: "Macon", state: "GA" },
  { city: "Valdosta", state: "GA" },
  { city: "Peachtree City", state: "GA" },
  { city: "Gainesville", state: "GA" },
  { city: "Hinesville", state: "GA" },
  { city: "Rome", state: "GA" },
  { city: "Norcross", state: "GA" },
  { city: "Tucker", state: "GA" },
  { city: "Lawrenceville", state: "GA" },
  { city: "Duluth", state: "GA" },
  { city: "Peachtree Corners", state: "GA" },
  { city: "Cumming", state: "GA" },
  { city: "Milton", state: "GA" },
  { city: "Woodstock", state: "GA" },
  { city: "Canton", state: "GA" },
  { city: "Acworth", state: "GA" },
  { city: "Kennesaw", state: "GA" },
  { city: "Powder Springs", state: "GA" },
  { city: "Douglasville", state: "GA" },
  { city: "Newnan", state: "GA" },
  { city: "Fayetteville", state: "GA" },
  { city: "Stockbridge", state: "GA" },
  { city: "McDonough", state: "GA" },
  // Hawaii
  { city: "Honolulu", state: "HI" },
  { city: "Hilo", state: "HI" },
  { city: "Kailua", state: "HI" },
  { city: "Pearl City", state: "HI" },
  { city: "Waipahu", state: "HI" },
  { city: "Kaneohe", state: "HI" },
  { city: "Mililani", state: "HI" },
  { city: "Ewa Beach", state: "HI" },
  { city: "Kapolei", state: "HI" },
  { city: "Kahului", state: "HI" },
  { city: "Kihei", state: "HI" },
  { city: "Lahaina", state: "HI" },
  { city: "Wailuku", state: "HI" },
  { city: "Makawao", state: "HI" },
  { city: "Paia", state: "HI" },
  { city: "Kona", state: "HI" },
  { city: "Waimea", state: "HI" },
  { city: "Lihue", state: "HI" },
  { city: "Kapaa", state: "HI" },
  { city: "Princeville", state: "HI" },
  { city: "Poipu", state: "HI" },
  { city: "Haleiwa", state: "HI" },
  { city: "Waikiki", state: "HI" },
  { city: "Diamond Head", state: "HI" },
  // Idaho
  { city: "Boise", state: "ID" },
  { city: "Meridian", state: "ID" },
  { city: "Nampa", state: "ID" },
  { city: "Idaho Falls", state: "ID" },
  { city: "Pocatello", state: "ID" },
  { city: "Coeur d'Alene", state: "ID" },
  { city: "Twin Falls", state: "ID" },
  { city: "Caldwell", state: "ID" },
  { city: "Post Falls", state: "ID" },
  { city: "Lewiston", state: "ID" },
  { city: "Sandpoint", state: "ID" },
  { city: "Sun Valley", state: "ID" },
  { city: "Hailey", state: "ID" },
  // Illinois
  { city: "Chicago", state: "IL" },
  { city: "Aurora", state: "IL" },
  { city: "Joliet", state: "IL" },
  { city: "Naperville", state: "IL" },
  { city: "Rockford", state: "IL" },
  { city: "Springfield", state: "IL" },
  { city: "Elgin", state: "IL" },
  { city: "Peoria", state: "IL" },
  { city: "Champaign", state: "IL" },
  { city: "Waukegan", state: "IL" },
  { city: "Evanston", state: "IL" },
  { city: "Oak Park", state: "IL" },
  { city: "Schaumburg", state: "IL" },
  { city: "Bolingbrook", state: "IL" },
  { city: "Palatine", state: "IL" },
  { city: "Skokie", state: "IL" },
  { city: "Des Plaines", state: "IL" },
  { city: "Orland Park", state: "IL" },
  { city: "Tinley Park", state: "IL" },
  { city: "Oak Lawn", state: "IL" },
  { city: "Berwyn", state: "IL" },
  { city: "Mount Prospect", state: "IL" },
  { city: "Wheaton", state: "IL" },
  { city: "Downers Grove", state: "IL" },
  { city: "Lombard", state: "IL" },
  { city: "Glenview", state: "IL" },
  { city: "Buffalo Grove", state: "IL" },
  { city: "Hoffman Estates", state: "IL" },
  { city: "Arlington Heights", state: "IL" },
  { city: "Bartlett", state: "IL" },
  { city: "Carol Stream", state: "IL" },
  { city: "Streamwood", state: "IL" },
  { city: "Crystal Lake", state: "IL" },
  { city: "Lake Zurich", state: "IL" },
  { city: "Libertyville", state: "IL" },
  { city: "Vernon Hills", state: "IL" },
  { city: "Mundelein", state: "IL" },
  { city: "Lake Forest", state: "IL" },
  { city: "Highland Park", state: "IL" },
  { city: "Glencoe", state: "IL" },
  { city: "Winnetka", state: "IL" },
  { city: "Wilmette", state: "IL" },
  { city: "Kenilworth", state: "IL" },
  // Indiana
  { city: "Indianapolis", state: "IN" },
  { city: "Fort Wayne", state: "IN" },
  { city: "Evansville", state: "IN" },
  { city: "South Bend", state: "IN" },
  { city: "Carmel", state: "IN" },
  { city: "Bloomington", state: "IN" },
  { city: "Fishers", state: "IN" },
  { city: "Hammond", state: "IN" },
  { city: "Gary", state: "IN" },
  { city: "Muncie", state: "IN" },
  { city: "Lafayette", state: "IN" },
  { city: "Terre Haute", state: "IN" },
  { city: "Noblesville", state: "IN" },
  { city: "Anderson", state: "IN" },
  { city: "Westfield", state: "IN" },
  { city: "Greenwood", state: "IN" },
  { city: "Columbus", state: "IN" },
  { city: "Kokomo", state: "IN" },
  { city: "Zionsville", state: "IN" },
  // Iowa
  { city: "Des Moines", state: "IA" },
  { city: "Cedar Rapids", state: "IA" },
  { city: "Davenport", state: "IA" },
  { city: "Sioux City", state: "IA" },
  { city: "Iowa City", state: "IA" },
  { city: "Waterloo", state: "IA" },
  { city: "Ames", state: "IA" },
  { city: "Dubuque", state: "IA" },
  { city: "Ankeny", state: "IA" },
  { city: "West Des Moines", state: "IA" },
  { city: "Council Bluffs", state: "IA" },
  // Kansas
  { city: "Wichita", state: "KS" },
  { city: "Overland Park", state: "KS" },
  { city: "Kansas City", state: "KS" },
  { city: "Topeka", state: "KS" },
  { city: "Olathe", state: "KS" },
  { city: "Lawrence", state: "KS" },
  { city: "Shawnee", state: "KS" },
  { city: "Manhattan", state: "KS" },
  { city: "Lenexa", state: "KS" },
  { city: "Salina", state: "KS" },
  { city: "Leawood", state: "KS" },
  { city: "Leavenworth", state: "KS" },
  // Kentucky
  { city: "Louisville", state: "KY" },
  { city: "Lexington", state: "KY" },
  { city: "Bowling Green", state: "KY" },
  { city: "Owensboro", state: "KY" },
  { city: "Covington", state: "KY" },
  { city: "Elizabethtown", state: "KY" },
  { city: "Florence", state: "KY" },
  { city: "Georgetown", state: "KY" },
  { city: "Paducah", state: "KY" },
  { city: "Henderson", state: "KY" },
  { city: "Richmond", state: "KY" },
  // Louisiana
  { city: "New Orleans", state: "LA" },
  { city: "Baton Rouge", state: "LA" },
  { city: "Shreveport", state: "LA" },
  { city: "Metairie", state: "LA" },
  { city: "Lafayette", state: "LA" },
  { city: "Lake Charles", state: "LA" },
  { city: "Kenner", state: "LA" },
  { city: "Bossier City", state: "LA" },
  { city: "Monroe", state: "LA" },
  { city: "Alexandria", state: "LA" },
  { city: "Hammond", state: "LA" },
  { city: "Slidell", state: "LA" },
  { city: "Covington", state: "LA" },
  { city: "Mandeville", state: "LA" },
  // Maine
  { city: "Portland", state: "ME" },
  { city: "Augusta", state: "ME" },
  { city: "Bangor", state: "ME" },
  { city: "Lewiston", state: "ME" },
  { city: "South Portland", state: "ME" },
  { city: "Biddeford", state: "ME" },
  { city: "Sanford", state: "ME" },
  { city: "Kennebunkport", state: "ME" },
  { city: "Bar Harbor", state: "ME" },
  { city: "Ogunquit", state: "ME" },
  { city: "Rockport", state: "ME" },
  { city: "Camden", state: "ME" },
  // Maryland
  { city: "Baltimore", state: "MD" },
  { city: "Frederick", state: "MD" },
  { city: "Rockville", state: "MD" },
  { city: "Gaithersburg", state: "MD" },
  { city: "Bowie", state: "MD" },
  { city: "Annapolis", state: "MD" },
  { city: "Bethesda", state: "MD" },
  { city: "Silver Spring", state: "MD" },
  { city: "College Park", state: "MD" },
  { city: "Hagerstown", state: "MD" },
  { city: "Salisbury", state: "MD" },
  { city: "Laurel", state: "MD" },
  { city: "Greenbelt", state: "MD" },
  { city: "Columbia", state: "MD" },
  { city: "Ellicott City", state: "MD" },
  { city: "Towson", state: "MD" },
  { city: "Catonsville", state: "MD" },
  { city: "Dundalk", state: "MD" },
  { city: "Waldorf", state: "MD" },
  { city: "Germantown", state: "MD" },
  { city: "Potomac", state: "MD" },
  { city: "Chevy Chase", state: "MD" },
  { city: "Kensington", state: "MD" },
  { city: "Takoma Park", state: "MD" },
  { city: "Ocean City", state: "MD" },
  { city: "Cumberland", state: "MD" },
  { city: "Easton", state: "MD" },
  // Massachusetts
  { city: "Boston", state: "MA" },
  { city: "Worcester", state: "MA" },
  { city: "Springfield", state: "MA" },
  { city: "Lowell", state: "MA" },
  { city: "Cambridge", state: "MA" },
  { city: "New Bedford", state: "MA" },
  { city: "Brockton", state: "MA" },
  { city: "Quincy", state: "MA" },
  { city: "Lynn", state: "MA" },
  { city: "Fall River", state: "MA" },
  { city: "Newton", state: "MA" },
  { city: "Somerville", state: "MA" },
  { city: "Medford", state: "MA" },
  { city: "Framingham", state: "MA" },
  { city: "Haverhill", state: "MA" },
  { city: "Malden", state: "MA" },
  { city: "Waltham", state: "MA" },
  { city: "Taunton", state: "MA" },
  { city: "Revere", state: "MA" },
  { city: "Methuen", state: "MA" },
  { city: "Weymouth", state: "MA" },
  { city: "Peabody", state: "MA" },
  { city: "Chicopee", state: "MA" },
  { city: "Attleboro", state: "MA" },
  { city: "Salem", state: "MA" },
  { city: "Gloucester", state: "MA" },
  { city: "Lexington", state: "MA" },
  { city: "Concord", state: "MA" },
  { city: "Brookline", state: "MA" },
  { city: "Watertown", state: "MA" },
  { city: "Arlington", state: "MA" },
  { city: "Belmont", state: "MA" },
  { city: "Natick", state: "MA" },
  { city: "Needham", state: "MA" },
  { city: "Wellesley", state: "MA" },
  { city: "Weston", state: "MA" },
  { city: "Dedham", state: "MA" },
  { city: "Canton", state: "MA" },
  { city: "Norwood", state: "MA" },
  { city: "Stoughton", state: "MA" },
  { city: "Randolph", state: "MA" },
  { city: "Milton", state: "MA" },
  { city: "Dorchester", state: "MA" },
  { city: "South Boston", state: "MA" },
  { city: "Back Bay", state: "MA" },
  { city: "Beacon Hill", state: "MA" },
  { city: "Fenway", state: "MA" },
  { city: "North End", state: "MA" },
  { city: "Charlestown", state: "MA" },
  { city: "East Boston", state: "MA" },
  { city: "Nantucket", state: "MA" },
  { city: "Martha's Vineyard", state: "MA" },
  { city: "Falmouth", state: "MA" },
  { city: "Barnstable", state: "MA" },
  { city: "Hyannis", state: "MA" },
  { city: "Sandwich", state: "MA" },
  { city: "Dennis", state: "MA" },
  { city: "Harwich", state: "MA" },
  { city: "Chatham", state: "MA" },
  { city: "Orleans", state: "MA" },
  { city: "Wellfleet", state: "MA" },
  { city: "Provincetown", state: "MA" },
  { city: "Plymouth", state: "MA" },
  { city: "Duxbury", state: "MA" },
  { city: "Marshfield", state: "MA" },
  { city: "Scituate", state: "MA" },
  { city: "Cohasset", state: "MA" },
  { city: "Hull", state: "MA" },
  { city: "Hingham", state: "MA" },
  // Michigan
  { city: "Detroit", state: "MI" },
  { city: "Grand Rapids", state: "MI" },
  { city: "Warren", state: "MI" },
  { city: "Sterling Heights", state: "MI" },
  { city: "Ann Arbor", state: "MI" },
  { city: "Lansing", state: "MI" },
  { city: "Flint", state: "MI" },
  { city: "Dearborn", state: "MI" },
  { city: "Livonia", state: "MI" },
  { city: "Troy", state: "MI" },
  { city: "Kalamazoo", state: "MI" },
  { city: "Traverse City", state: "MI" },
  { city: "Wyoming", state: "MI" },
  { city: "Westland", state: "MI" },
  { city: "Southfield", state: "MI" },
  { city: "East Lansing", state: "MI" },
  { city: "Dearborn Heights", state: "MI" },
  { city: "Taylor", state: "MI" },
  { city: "Saginaw", state: "MI" },
  { city: "Pontiac", state: "MI" },
  { city: "Royal Oak", state: "MI" },
  { city: "Farmington Hills", state: "MI" },
  { city: "Clinton Township", state: "MI" },
  { city: "Canton", state: "MI" },
  { city: "Rochester Hills", state: "MI" },
  { city: "Novi", state: "MI" },
  { city: "West Bloomfield", state: "MI" },
  { city: "Bloomfield Hills", state: "MI" },
  { city: "Birmingham", state: "MI" },
  { city: "Auburn Hills", state: "MI" },
  { city: "Macomb", state: "MI" },
  { city: "Shelby Township", state: "MI" },
  { city: "Grosse Pointe", state: "MI" },
  { city: "Mount Pleasant", state: "MI" },
  { city: "Holland", state: "MI" },
  { city: "Muskegon", state: "MI" },
  { city: "Midland", state: "MI" },
  { city: "Bay City", state: "MI" },
  { city: "Marquette", state: "MI" },
  { city: "Petoskey", state: "MI" },
  // Minnesota
  { city: "Minneapolis", state: "MN" },
  { city: "St. Paul", state: "MN" },
  { city: "Rochester", state: "MN" },
  { city: "Duluth", state: "MN" },
  { city: "Bloomington", state: "MN" },
  { city: "Brooklyn Park", state: "MN" },
  { city: "Plymouth", state: "MN" },
  { city: "Maple Grove", state: "MN" },
  { city: "Woodbury", state: "MN" },
  { city: "St. Cloud", state: "MN" },
  { city: "Eagan", state: "MN" },
  { city: "Burnsville", state: "MN" },
  { city: "Lakeville", state: "MN" },
  { city: "Blaine", state: "MN" },
  { city: "Minnetonka", state: "MN" },
  { city: "Eden Prairie", state: "MN" },
  { city: "Coon Rapids", state: "MN" },
  { city: "Edina", state: "MN" },
  { city: "St. Louis Park", state: "MN" },
  { city: "Richfield", state: "MN" },
  { city: "Moorhead", state: "MN" },
  { city: "Apple Valley", state: "MN" },
  { city: "Stillwater", state: "MN" },
  { city: "Prior Lake", state: "MN" },
  { city: "Shakopee", state: "MN" },
  // Mississippi
  { city: "Jackson", state: "MS" },
  { city: "Gulfport", state: "MS" },
  { city: "Biloxi", state: "MS" },
  { city: "Hattiesburg", state: "MS" },
  { city: "Southaven", state: "MS" },
  { city: "Meridian", state: "MS" },
  { city: "Tupelo", state: "MS" },
  { city: "Olive Branch", state: "MS" },
  { city: "Pascagoula", state: "MS" },
  { city: "Ocean Springs", state: "MS" },
  // Missouri
  { city: "Kansas City", state: "MO" },
  { city: "St. Louis", state: "MO" },
  { city: "Springfield", state: "MO" },
  { city: "Columbia", state: "MO" },
  { city: "Independence", state: "MO" },
  { city: "Lee's Summit", state: "MO" },
  { city: "O'Fallon", state: "MO" },
  { city: "St. Joseph", state: "MO" },
  { city: "St. Charles", state: "MO" },
  { city: "St. Peters", state: "MO" },
  { city: "Blue Springs", state: "MO" },
  { city: "Florissant", state: "MO" },
  { city: "Joplin", state: "MO" },
  { city: "Chesterfield", state: "MO" },
  { city: "Jefferson City", state: "MO" },
  { city: "Kirkwood", state: "MO" },
  { city: "Clayton", state: "MO" },
  { city: "Ladue", state: "MO" },
  { city: "Branson", state: "MO" },
  { city: "Cape Girardeau", state: "MO" },
  // Montana
  { city: "Billings", state: "MT" },
  { city: "Missoula", state: "MT" },
  { city: "Great Falls", state: "MT" },
  { city: "Bozeman", state: "MT" },
  { city: "Butte", state: "MT" },
  { city: "Helena", state: "MT" },
  { city: "Kalispell", state: "MT" },
  { city: "Whitefish", state: "MT" },
  // Nebraska
  { city: "Omaha", state: "NE" },
  { city: "Lincoln", state: "NE" },
  { city: "Bellevue", state: "NE" },
  { city: "Grand Island", state: "NE" },
  { city: "Kearney", state: "NE" },
  { city: "Fremont", state: "NE" },
  { city: "Hastings", state: "NE" },
  { city: "Norfolk", state: "NE" },
  // Nevada
  { city: "Las Vegas", state: "NV" },
  { city: "Henderson", state: "NV" },
  { city: "Reno", state: "NV" },
  { city: "North Las Vegas", state: "NV" },
  { city: "Sparks", state: "NV" },
  { city: "Carson City", state: "NV" },
  { city: "Enterprise", state: "NV" },
  { city: "Summerlin", state: "NV" },
  { city: "Spring Valley", state: "NV" },
  { city: "Paradise", state: "NV" },
  { city: "Boulder City", state: "NV" },
  { city: "Laughlin", state: "NV" },
  { city: "Mesquite", state: "NV" },
  // New Hampshire
  { city: "Manchester", state: "NH" },
  { city: "Nashua", state: "NH" },
  { city: "Concord", state: "NH" },
  { city: "Derry", state: "NH" },
  { city: "Dover", state: "NH" },
  { city: "Rochester", state: "NH" },
  { city: "Salem", state: "NH" },
  { city: "Merrimack", state: "NH" },
  { city: "Portsmouth", state: "NH" },
  { city: "Laconia", state: "NH" },
  { city: "Keene", state: "NH" },
  { city: "Hanover", state: "NH" },
  // New Jersey
  { city: "Newark", state: "NJ" },
  { city: "Jersey City", state: "NJ" },
  { city: "Paterson", state: "NJ" },
  { city: "Elizabeth", state: "NJ" },
  { city: "Edison", state: "NJ" },
  { city: "Woodbridge", state: "NJ" },
  { city: "Lakewood", state: "NJ" },
  { city: "Toms River", state: "NJ" },
  { city: "Hamilton", state: "NJ" },
  { city: "Trenton", state: "NJ" },
  { city: "Clifton", state: "NJ" },
  { city: "Camden", state: "NJ" },
  { city: "Hoboken", state: "NJ" },
  { city: "Princeton", state: "NJ" },
  { city: "Atlantic City", state: "NJ" },
  { city: "Cherry Hill", state: "NJ" },
  { city: "Passaic", state: "NJ" },
  { city: "Union City", state: "NJ" },
  { city: "Bayonne", state: "NJ" },
  { city: "East Orange", state: "NJ" },
  { city: "Irvington", state: "NJ" },
  { city: "Vineland", state: "NJ" },
  { city: "New Brunswick", state: "NJ" },
  { city: "Perth Amboy", state: "NJ" },
  { city: "Plainfield", state: "NJ" },
  { city: "Hackensack", state: "NJ" },
  { city: "Sayreville", state: "NJ" },
  { city: "Kearny", state: "NJ" },
  { city: "Linden", state: "NJ" },
  { city: "Camden", state: "NJ" },
  { city: "Fort Lee", state: "NJ" },
  { city: "Englewood", state: "NJ" },
  { city: "Teaneck", state: "NJ" },
  { city: "Paramus", state: "NJ" },
  { city: "Ridgewood", state: "NJ" },
  { city: "Montclair", state: "NJ" },
  { city: "Bloomfield", state: "NJ" },
  { city: "West Orange", state: "NJ" },
  { city: "South Orange", state: "NJ" },
  { city: "Maplewood", state: "NJ" },
  { city: "Millburn", state: "NJ" },
  { city: "Short Hills", state: "NJ" },
  { city: "Summit", state: "NJ" },
  { city: "Westfield", state: "NJ" },
  { city: "Cranford", state: "NJ" },
  { city: "Scotch Plains", state: "NJ" },
  { city: "Fanwood", state: "NJ" },
  { city: "Rahway", state: "NJ" },
  { city: "Roselle", state: "NJ" },
  { city: "Metuchen", state: "NJ" },
  { city: "Piscataway", state: "NJ" },
  { city: "North Brunswick", state: "NJ" },
  { city: "South Brunswick", state: "NJ" },
  { city: "East Brunswick", state: "NJ" },
  { city: "Monroe Township", state: "NJ" },
  { city: "Marlboro", state: "NJ" },
  { city: "Manalapan", state: "NJ" },
  { city: "Freehold", state: "NJ" },
  { city: "Ocean Township", state: "NJ" },
  { city: "Brick", state: "NJ" },
  { city: "Wall Township", state: "NJ" },
  { city: "Sea Girt", state: "NJ" },
  { city: "Spring Lake", state: "NJ" },
  { city: "Asbury Park", state: "NJ" },
  { city: "Long Branch", state: "NJ" },
  { city: "Red Bank", state: "NJ" },
  { city: "Rumson", state: "NJ" },
  { city: "Shrewsbury", state: "NJ" },
  { city: "Colts Neck", state: "NJ" },
  { city: "Holmdel", state: "NJ" },
  { city: "Middletown", state: "NJ" },
  { city: "Hazlet", state: "NJ" },
  { city: "Keyport", state: "NJ" },
  { city: "Keansburg", state: "NJ" },
  // New Mexico
  { city: "Albuquerque", state: "NM" },
  { city: "Las Cruces", state: "NM" },
  { city: "Rio Rancho", state: "NM" },
  { city: "Santa Fe", state: "NM" },
  { city: "Roswell", state: "NM" },
  { city: "Farmington", state: "NM" },
  { city: "Taos", state: "NM" },
  { city: "Clovis", state: "NM" },
  { city: "Hobbs", state: "NM" },
  // New York
  { city: "New York City", state: "NY" },
  { city: "Manhattan", state: "NY" },
  { city: "Brooklyn", state: "NY" },
  { city: "Queens", state: "NY" },
  { city: "Bronx", state: "NY" },
  { city: "Staten Island", state: "NY" },
  { city: "Buffalo", state: "NY" },
  { city: "Rochester", state: "NY" },
  { city: "Yonkers", state: "NY" },
  { city: "Syracuse", state: "NY" },
  { city: "Albany", state: "NY" },
  { city: "New Rochelle", state: "NY" },
  { city: "Mount Vernon", state: "NY" },
  { city: "Schenectady", state: "NY" },
  { city: "Utica", state: "NY" },
  { city: "White Plains", state: "NY" },
  { city: "Hempstead", state: "NY" },
  { city: "Troy", state: "NY" },
  { city: "Niagara Falls", state: "NY" },
  { city: "Ithaca", state: "NY" },
  { city: "Long Island City", state: "NY" },
  { city: "Flushing", state: "NY" },
  { city: "Astoria", state: "NY" },
  { city: "Harlem", state: "NY" },
  { city: "Williamsburg", state: "NY" },
  { city: "Park Slope", state: "NY" },
  { city: "DUMBO", state: "NY" },
  { city: "Chelsea", state: "NY" },
  { city: "SoHo", state: "NY" },
  { city: "Tribeca", state: "NY" },
  { city: "Financial District", state: "NY" },
  { city: "Upper East Side", state: "NY" },
  { city: "Upper West Side", state: "NY" },
  { city: "Midtown", state: "NY" },
  { city: "Gramercy", state: "NY" },
  { city: "East Village", state: "NY" },
  { city: "West Village", state: "NY" },
  { city: "Greenwich Village", state: "NY" },
  { city: "Flatiron", state: "NY" },
  { city: "Murray Hill", state: "NY" },
  { city: "Kips Bay", state: "NY" },
  { city: "Meatpacking District", state: "NY" },
  { city: "Hell's Kitchen", state: "NY" },
  { city: "Times Square", state: "NY" },
  { city: "Midtown East", state: "NY" },
  { city: "Sutton Place", state: "NY" },
  { city: "Turtle Bay", state: "NY" },
  { city: "Lenox Hill", state: "NY" },
  { city: "Yorkville", state: "NY" },
  { city: "Carnegie Hill", state: "NY" },
  { city: "Inwood", state: "NY" },
  { city: "Washington Heights", state: "NY" },
  { city: "Marble Hill", state: "NY" },
  { city: "Riverdale", state: "NY" },
  { city: "Southampton", state: "NY" },
  { city: "East Hampton", state: "NY" },
  { city: "Bridgehampton", state: "NY" },
  { city: "Sag Harbor", state: "NY" },
  { city: "Water Mill", state: "NY" },
  { city: "Montauk", state: "NY" },
  { city: "Shelter Island", state: "NY" },
  { city: "Greenport", state: "NY" },
  { city: "Riverhead", state: "NY" },
  { city: "Garden City", state: "NY" },
  { city: "Mineola", state: "NY" },
  { city: "Westbury", state: "NY" },
  { city: "Hicksville", state: "NY" },
  { city: "Levittown", state: "NY" },
  { city: "Bethpage", state: "NY" },
  { city: "Plainview", state: "NY" },
  { city: "Syosset", state: "NY" },
  { city: "Jericho", state: "NY" },
  { city: "Woodbury", state: "NY" },
  { city: "Cold Spring Harbor", state: "NY" },
  { city: "Huntington", state: "NY" },
  { city: "Northport", state: "NY" },
  { city: "Commack", state: "NY" },
  { city: "Hauppauge", state: "NY" },
  { city: "Smithtown", state: "NY" },
  { city: "St. James", state: "NY" },
  { city: "Stony Brook", state: "NY" },
  { city: "Port Jefferson", state: "NY" },
  { city: "Setauket", state: "NY" },
  { city: "Centereach", state: "NY" },
  { city: "Patchogue", state: "NY" },
  { city: "Islip", state: "NY" },
  { city: "Bay Shore", state: "NY" },
  { city: "Babylon", state: "NY" },
  { city: "Lindenhurst", state: "NY" },
  { city: "Amityville", state: "NY" },
  { city: "Massapequa", state: "NY" },
  { city: "Merrick", state: "NY" },
  { city: "Bellmore", state: "NY" },
  { city: "Wantagh", state: "NY" },
  { city: "Seaford", state: "NY" },
  { city: "Rockville Centre", state: "NY" },
  { city: "Lynbrook", state: "NY" },
  { city: "Valley Stream", state: "NY" },
  { city: "Elmont", state: "NY" },
  { city: "Jamaica", state: "NY" },
  { city: "Howard Beach", state: "NY" },
  { city: "Bayside", state: "NY" },
  { city: "Forest Hills", state: "NY" },
  { city: "Ridgewood", state: "NY" },
  { city: "Middle Village", state: "NY" },
  { city: "Ozone Park", state: "NY" },
  { city: "Woodhaven", state: "NY" },
  { city: "Rego Park", state: "NY" },
  { city: "Jackson Heights", state: "NY" },
  { city: "Elmhurst", state: "NY" },
  { city: "Corona", state: "NY" },
  { city: "Woodside", state: "NY" },
  { city: "Sunnyside", state: "NY" },
  { city: "Maspeth", state: "NY" },
  { city: "Glendale", state: "NY" },
  { city: "Richmond Hill", state: "NY" },
  { city: "South Ozone Park", state: "NY" },
  { city: "Rosedale", state: "NY" },
  { city: "Bronxville", state: "NY" },
  { city: "Scarsdale", state: "NY" },
  { city: "Mamaroneck", state: "NY" },
  { city: "Larchmont", state: "NY" },
  { city: "Harrison", state: "NY" },
  { city: "Rye", state: "NY" },
  { city: "Port Chester", state: "NY" },
  { city: "Greenwich", state: "NY" },
  { city: "Tarrytown", state: "NY" },
  { city: "Pleasantville", state: "NY" },
  { city: "Ossining", state: "NY" },
  { city: "Peekskill", state: "NY" },
  { city: "Poughkeepsie", state: "NY" },
  { city: "Kingston", state: "NY" },
  { city: "Newburgh", state: "NY" },
  { city: "Middletown", state: "NY" },
  { city: "Saratoga Springs", state: "NY" },
  { city: "Glens Falls", state: "NY" },
  // North Carolina
  { city: "Charlotte", state: "NC" },
  { city: "Raleigh", state: "NC" },
  { city: "Greensboro", state: "NC" },
  { city: "Durham", state: "NC" },
  { city: "Winston-Salem", state: "NC" },
  { city: "Fayetteville", state: "NC" },
  { city: "Cary", state: "NC" },
  { city: "Wilmington", state: "NC" },
  { city: "High Point", state: "NC" },
  { city: "Chapel Hill", state: "NC" },
  { city: "Asheville", state: "NC" },
  { city: "Concord", state: "NC" },
  { city: "Gastonia", state: "NC" },
  { city: "Jacksonville", state: "NC" },
  { city: "Huntersville", state: "NC" },
  { city: "Rocky Mount", state: "NC" },
  { city: "Greenville", state: "NC" },
  { city: "Burlington", state: "NC" },
  { city: "Kannapolis", state: "NC" },
  { city: "Apex", state: "NC" },
  { city: "Holly Springs", state: "NC" },
  { city: "Mooresville", state: "NC" },
  { city: "Cornelius", state: "NC" },
  { city: "Pinehurst", state: "NC" },
  { city: "Southern Pines", state: "NC" },
  { city: "Matthews", state: "NC" },
  { city: "Mint Hill", state: "NC" },
  { city: "Monroe", state: "NC" },
  // North Dakota
  { city: "Fargo", state: "ND" },
  { city: "Bismarck", state: "ND" },
  { city: "Grand Forks", state: "ND" },
  { city: "Minot", state: "ND" },
  { city: "West Fargo", state: "ND" },
  // Ohio
  { city: "Columbus", state: "OH" },
  { city: "Cleveland", state: "OH" },
  { city: "Cincinnati", state: "OH" },
  { city: "Toledo", state: "OH" },
  { city: "Akron", state: "OH" },
  { city: "Dayton", state: "OH" },
  { city: "Parma", state: "OH" },
  { city: "Canton", state: "OH" },
  { city: "Youngstown", state: "OH" },
  { city: "Lorain", state: "OH" },
  { city: "Hamilton", state: "OH" },
  { city: "Springfield", state: "OH" },
  { city: "Kettering", state: "OH" },
  { city: "Elyria", state: "OH" },
  { city: "Newark", state: "OH" },
  { city: "Lakewood", state: "OH" },
  { city: "Cuyahoga Falls", state: "OH" },
  { city: "Mentor", state: "OH" },
  { city: "Euclid", state: "OH" },
  { city: "Middletown", state: "OH" },
  { city: "Dublin", state: "OH" },
  { city: "Westerville", state: "OH" },
  { city: "Upper Arlington", state: "OH" },
  { city: "Beavercreek", state: "OH" },
  { city: "Fairfield", state: "OH" },
  { city: "Mason", state: "OH" },
  { city: "Strongsville", state: "OH" },
  { city: "North Olmsted", state: "OH" },
  { city: "Medina", state: "OH" },
  { city: "Wooster", state: "OH" },
  { city: "Zanesville", state: "OH" },
  { city: "Lancaster", state: "OH" },
  // Oklahoma
  { city: "Oklahoma City", state: "OK" },
  { city: "Tulsa", state: "OK" },
  { city: "Norman", state: "OK" },
  { city: "Broken Arrow", state: "OK" },
  { city: "Lawton", state: "OK" },
  { city: "Edmond", state: "OK" },
  { city: "Moore", state: "OK" },
  { city: "Midwest City", state: "OK" },
  { city: "Enid", state: "OK" },
  { city: "Stillwater", state: "OK" },
  { city: "Owasso", state: "OK" },
  { city: "Bixby", state: "OK" },
  { city: "Jenks", state: "OK" },
  // Oregon
  { city: "Portland", state: "OR" },
  { city: "Salem", state: "OR" },
  { city: "Eugene", state: "OR" },
  { city: "Gresham", state: "OR" },
  { city: "Hillsboro", state: "OR" },
  { city: "Beaverton", state: "OR" },
  { city: "Bend", state: "OR" },
  { city: "Medford", state: "OR" },
  { city: "Springfield", state: "OR" },
  { city: "Corvallis", state: "OR" },
  { city: "Albany", state: "OR" },
  { city: "Lake Oswego", state: "OR" },
  { city: "Tigard", state: "OR" },
  { city: "Tualatin", state: "OR" },
  { city: "Sherwood", state: "OR" },
  { city: "Wilsonville", state: "OR" },
  { city: "West Linn", state: "OR" },
  { city: "Canby", state: "OR" },
  { city: "McMinnville", state: "OR" },
  { city: "Newberg", state: "OR" },
  { city: "Grants Pass", state: "OR" },
  { city: "Ashland", state: "OR" },
  { city: "Klamath Falls", state: "OR" },
  { city: "Redmond", state: "OR" },
  { city: "Sisters", state: "OR" },
  { city: "Hood River", state: "OR" },
  { city: "The Dalles", state: "OR" },
  { city: "Lincoln City", state: "OR" },
  { city: "Newport", state: "OR" },
  { city: "Florence", state: "OR" },
  { city: "Coos Bay", state: "OR" },
  // Pennsylvania
  { city: "Philadelphia", state: "PA" },
  { city: "Pittsburgh", state: "PA" },
  { city: "Allentown", state: "PA" },
  { city: "Erie", state: "PA" },
  { city: "Reading", state: "PA" },
  { city: "Scranton", state: "PA" },
  { city: "Bethlehem", state: "PA" },
  { city: "Lancaster", state: "PA" },
  { city: "Harrisburg", state: "PA" },
  { city: "York", state: "PA" },
  { city: "Altoona", state: "PA" },
  { city: "Wilkes-Barre", state: "PA" },
  { city: "Chester", state: "PA" },
  { city: "Easton", state: "PA" },
  { city: "King of Prussia", state: "PA" },
  { city: "Wayne", state: "PA" },
  { city: "Ardmore", state: "PA" },
  { city: "Bryn Mawr", state: "PA" },
  { city: "Radnor", state: "PA" },
  { city: "Malvern", state: "PA" },
  { city: "West Chester", state: "PA" },
  { city: "Exton", state: "PA" },
  { city: "Downingtown", state: "PA" },
  { city: "Kennett Square", state: "PA" },
  { city: "Media", state: "PA" },
  { city: "Newtown Square", state: "PA" },
  { city: "Villanova", state: "PA" },
  { city: "Haverford", state: "PA" },
  { city: "Havertown", state: "PA" },
  { city: "Springfield", state: "PA" },
  { city: "Drexel Hill", state: "PA" },
  { city: "Upper Darby", state: "PA" },
  { city: "Norristown", state: "PA" },
  { city: "Lansdale", state: "PA" },
  { city: "Horsham", state: "PA" },
  { city: "Doylestown", state: "PA" },
  { city: "New Hope", state: "PA" },
  { city: "Newtown", state: "PA" },
  { city: "Bucks County", state: "PA" },
  // Rhode Island
  { city: "Providence", state: "RI" },
  { city: "Warwick", state: "RI" },
  { city: "Cranston", state: "RI" },
  { city: "Pawtucket", state: "RI" },
  { city: "East Providence", state: "RI" },
  { city: "Woonsocket", state: "RI" },
  { city: "Newport", state: "RI" },
  { city: "Middletown", state: "RI" },
  { city: "Narragansett", state: "RI" },
  // South Carolina
  { city: "Columbia", state: "SC" },
  { city: "Charleston", state: "SC" },
  { city: "North Charleston", state: "SC" },
  { city: "Mount Pleasant", state: "SC" },
  { city: "Greenville", state: "SC" },
  { city: "Myrtle Beach", state: "SC" },
  { city: "Hilton Head", state: "SC" },
  { city: "Summerville", state: "SC" },
  { city: "Rock Hill", state: "SC" },
  { city: "Spartanburg", state: "SC" },
  { city: "Florence", state: "SC" },
  { city: "Lexington", state: "SC" },
  { city: "Goose Creek", state: "SC" },
  { city: "Anderson", state: "SC" },
  { city: "Bluffton", state: "SC" },
  { city: "Beaufort", state: "SC" },
  { city: "James Island", state: "SC" },
  { city: "Johns Island", state: "SC" },
  { city: "Isle of Palms", state: "SC" },
  { city: "Sullivan's Island", state: "SC" },
  { city: "Folly Beach", state: "SC" },
  { city: "Kiawah Island", state: "SC" },
  { city: "Pawleys Island", state: "SC" },
  { city: "Conway", state: "SC" },
  // South Dakota
  { city: "Sioux Falls", state: "SD" },
  { city: "Rapid City", state: "SD" },
  { city: "Aberdeen", state: "SD" },
  { city: "Brookings", state: "SD" },
  // Tennessee
  { city: "Memphis", state: "TN" },
  { city: "Nashville", state: "TN" },
  { city: "Knoxville", state: "TN" },
  { city: "Chattanooga", state: "TN" },
  { city: "Clarksville", state: "TN" },
  { city: "Murfreesboro", state: "TN" },
  { city: "Franklin", state: "TN" },
  { city: "Jackson", state: "TN" },
  { city: "Johnson City", state: "TN" },
  { city: "Bartlett", state: "TN" },
  { city: "Hendersonville", state: "TN" },
  { city: "Smyrna", state: "TN" },
  { city: "Collierville", state: "TN" },
  { city: "Germantown", state: "TN" },
  { city: "Spring Hill", state: "TN" },
  { city: "Brentwood", state: "TN" },
  { city: "Gallatin", state: "TN" },
  { city: "Oak Ridge", state: "TN" },
  { city: "Kingsport", state: "TN" },
  // Texas
  { city: "Houston", state: "TX" },
  { city: "San Antonio", state: "TX" },
  { city: "Dallas", state: "TX" },
  { city: "Austin", state: "TX" },
  { city: "Fort Worth", state: "TX" },
  { city: "El Paso", state: "TX" },
  { city: "Arlington", state: "TX" },
  { city: "Corpus Christi", state: "TX" },
  { city: "Plano", state: "TX" },
  { city: "Laredo", state: "TX" },
  { city: "Lubbock", state: "TX" },
  { city: "Garland", state: "TX" },
  { city: "Irving", state: "TX" },
  { city: "Amarillo", state: "TX" },
  { city: "Grand Prairie", state: "TX" },
  { city: "Brownsville", state: "TX" },
  { city: "Pasadena", state: "TX" },
  { city: "McKinney", state: "TX" },
  { city: "Killeen", state: "TX" },
  { city: "Frisco", state: "TX" },
  { city: "McAllen", state: "TX" },
  { city: "Mesquite", state: "TX" },
  { city: "Midland", state: "TX" },
  { city: "Denton", state: "TX" },
  { city: "Waco", state: "TX" },
  { city: "Carrollton", state: "TX" },
  { city: "Round Rock", state: "TX" },
  { city: "Abilene", state: "TX" },
  { city: "Beaumont", state: "TX" },
  { city: "Odessa", state: "TX" },
  { city: "Richardson", state: "TX" },
  { city: "Pearland", state: "TX" },
  { city: "San Angelo", state: "TX" },
  { city: "Allen", state: "TX" },
  { city: "Sugar Land", state: "TX" },
  { city: "League City", state: "TX" },
  { city: "The Woodlands", state: "TX" },
  { city: "Tyler", state: "TX" },
  { city: "Galveston", state: "TX" },
  { city: "Lewisville", state: "TX" },
  { city: "Cedar Park", state: "TX" },
  { city: "Pflugerville", state: "TX" },
  { city: "Georgetown", state: "TX" },
  { city: "Flower Mound", state: "TX" },
  { city: "North Richland Hills", state: "TX" },
  { city: "Keller", state: "TX" },
  { city: "Southlake", state: "TX" },
  { city: "Colleyville", state: "TX" },
  { city: "Grapevine", state: "TX" },
  { city: "Euless", state: "TX" },
  { city: "Bedford", state: "TX" },
  { city: "Hurst", state: "TX" },
  { city: "Coppell", state: "TX" },
  { city: "Addison", state: "TX" },
  { city: "Highland Park", state: "TX" },
  { city: "University Park", state: "TX" },
  { city: "Uptown Dallas", state: "TX" },
  { city: "Deep Ellum", state: "TX" },
  { city: "Farmers Branch", state: "TX" },
  { city: "Duncanville", state: "TX" },
  { city: "Cedar Hill", state: "TX" },
  { city: "DeSoto", state: "TX" },
  { city: "Lancaster", state: "TX" },
  { city: "Mansfield", state: "TX" },
  { city: "Burleson", state: "TX" },
  { city: "Cleburne", state: "TX" },
  { city: "Weatherford", state: "TX" },
  { city: "Benbrook", state: "TX" },
  { city: "White Settlement", state: "TX" },
  { city: "Haltom City", state: "TX" },
  { city: "Watauga", state: "TX" },
  { city: "Saginaw", state: "TX" },
  { city: "Lake Worth", state: "TX" },
  { city: "Springtown", state: "TX" },
  { city: "Willow Park", state: "TX" },
  { city: "Aledo", state: "TX" },
  { city: "Azle", state: "TX" },
  { city: "Roanoke", state: "TX" },
  { city: "Trophy Club", state: "TX" },
  { city: "Westlake", state: "TX" },
  { city: "Corinth", state: "TX" },
  { city: "Argyle", state: "TX" },
  { city: "Bartonville", state: "TX" },
  { city: "Prosper", state: "TX" },
  { city: "Celina", state: "TX" },
  { city: "Anna", state: "TX" },
  { city: "Melissa", state: "TX" },
  { city: "Princeton", state: "TX" },
  { city: "Wylie", state: "TX" },
  { city: "Sachse", state: "TX" },
  { city: "Murphy", state: "TX" },
  { city: "Rowlett", state: "TX" },
  { city: "Sunnyvale", state: "TX" },
  { city: "Forney", state: "TX" },
  { city: "Royse City", state: "TX" },
  { city: "Rockwall", state: "TX" },
  { city: "Heath", state: "TX" },
  { city: "Fate", state: "TX" },
  { city: "Waxahachie", state: "TX" },
  { city: "Ennis", state: "TX" },
  { city: "Kyle", state: "TX" },
  { city: "Buda", state: "TX" },
  { city: "Bastrop", state: "TX" },
  { city: "Dripping Springs", state: "TX" },
  { city: "Lakeway", state: "TX" },
  { city: "Bee Cave", state: "TX" },
  { city: "West Lake Hills", state: "TX" },
  { city: "Rollingwood", state: "TX" },
  { city: "Spicewood", state: "TX" },
  { city: "Marble Falls", state: "TX" },
  { city: "Horseshoe Bay", state: "TX" },
  { city: "San Marcos", state: "TX" },
  { city: "Seguin", state: "TX" },
  { city: "New Braunfels", state: "TX" },
  { city: "Schertz", state: "TX" },
  { city: "Cibolo", state: "TX" },
  { city: "Converse", state: "TX" },
  { city: "Universal City", state: "TX" },
  { city: "Live Oak", state: "TX" },
  { city: "Leon Valley", state: "TX" },
  { city: "Helotes", state: "TX" },
  { city: "Boerne", state: "TX" },
  { city: "Bulverde", state: "TX" },
  { city: "Spring Branch", state: "TX" },
  { city: "Wimberley", state: "TX" },
  { city: "Canyon Lake", state: "TX" },
  { city: "Kerrville", state: "TX" },
  { city: "Fredericksburg", state: "TX" },
  { city: "Comfort", state: "TX" },
  { city: "Bandera", state: "TX" },
  { city: "Rockport", state: "TX" },
  { city: "Port Aransas", state: "TX" },
  { city: "Corpus Christi", state: "TX" },
  { city: "Victoria", state: "TX" },
  { city: "Bay City", state: "TX" },
  { city: "Angleton", state: "TX" },
  { city: "Lake Jackson", state: "TX" },
  { city: "Clute", state: "TX" },
  { city: "Texas City", state: "TX" },
  { city: "La Marque", state: "TX" },
  { city: "Friendswood", state: "TX" },
  { city: "Alvin", state: "TX" },
  { city: "Manvel", state: "TX" },
  { city: "Missouri City", state: "TX" },
  { city: "Stafford", state: "TX" },
  { city: "Katy", state: "TX" },
  { city: "Cypress", state: "TX" },
  { city: "Spring", state: "TX" },
  { city: "Humble", state: "TX" },
  { city: "Kingwood", state: "TX" },
  { city: "Conroe", state: "TX" },
  { city: "Magnolia", state: "TX" },
  { city: "Montgomery", state: "TX" },
  { city: "Tomball", state: "TX" },
  { city: "Porter", state: "TX" },
  { city: "Baytown", state: "TX" },
  { city: "La Porte", state: "TX" },
  { city: "Deer Park", state: "TX" },
  { city: "Seabrook", state: "TX" },
  { city: "Clear Lake City", state: "TX" },
  { city: "Webster", state: "TX" },
  { city: "El Lago", state: "TX" },
  { city: "Kemah", state: "TX" },
  { city: "Nassau Bay", state: "TX" },
  { city: "Galveston", state: "TX" },
  // Utah
  { city: "Salt Lake City", state: "UT" },
  { city: "West Valley City", state: "UT" },
  { city: "Provo", state: "UT" },
  { city: "West Jordan", state: "UT" },
  { city: "Orem", state: "UT" },
  { city: "Sandy", state: "UT" },
  { city: "St. George", state: "UT" },
  { city: "Park City", state: "UT" },
  { city: "Ogden", state: "UT" },
  { city: "Layton", state: "UT" },
  { city: "Murray", state: "UT" },
  { city: "South Jordan", state: "UT" },
  { city: "Herriman", state: "UT" },
  { city: "Draper", state: "UT" },
  { city: "Lehi", state: "UT" },
  { city: "Millcreek", state: "UT" },
  { city: "Taylorsville", state: "UT" },
  { city: "Cottonwood Heights", state: "UT" },
  { city: "Holladay", state: "UT" },
  { city: "Moab", state: "UT" },
  { city: "Cedar City", state: "UT" },
  { city: "Logan", state: "UT" },
  { city: "Bountiful", state: "UT" },
  { city: "Kaysville", state: "UT" },
  { city: "Farmington", state: "UT" },
  { city: "Clearfield", state: "UT" },
  { city: "Springville", state: "UT" },
  { city: "Spanish Fork", state: "UT" },
  { city: "American Fork", state: "UT" },
  { city: "Pleasant Grove", state: "UT" },
  { city: "Lindon", state: "UT" },
  // Vermont
  { city: "Burlington", state: "VT" },
  { city: "Montpelier", state: "VT" },
  { city: "Stowe", state: "VT" },
  { city: "Manchester", state: "VT" },
  { city: "Woodstock", state: "VT" },
  { city: "Rutland", state: "VT" },
  { city: "Middlebury", state: "VT" },
  { city: "Brattleboro", state: "VT" },
  // Virginia
  { city: "Virginia Beach", state: "VA" },
  { city: "Norfolk", state: "VA" },
  { city: "Chesapeake", state: "VA" },
  { city: "Richmond", state: "VA" },
  { city: "Newport News", state: "VA" },
  { city: "Alexandria", state: "VA" },
  { city: "Hampton", state: "VA" },
  { city: "Roanoke", state: "VA" },
  { city: "Arlington", state: "VA" },
  { city: "McLean", state: "VA" },
  { city: "Tysons", state: "VA" },
  { city: "Falls Church", state: "VA" },
  { city: "Fairfax", state: "VA" },
  { city: "Reston", state: "VA" },
  { city: "Herndon", state: "VA" },
  { city: "Sterling", state: "VA" },
  { city: "Leesburg", state: "VA" },
  { city: "Ashburn", state: "VA" },
  { city: "Loudoun County", state: "VA" },
  { city: "Manassas", state: "VA" },
  { city: "Woodbridge", state: "VA" },
  { city: "Stafford", state: "VA" },
  { city: "Fredericksburg", state: "VA" },
  { city: "Charlottesville", state: "VA" },
  { city: "Williamsburg", state: "VA" },
  { city: "Suffolk", state: "VA" },
  { city: "Portsmouth", state: "VA" },
  { city: "Lynchburg", state: "VA" },
  { city: "Harrisonburg", state: "VA" },
  { city: "Winchester", state: "VA" },
  { city: "Blacksburg", state: "VA" },
  { city: "Christiansburg", state: "VA" },
  { city: "Radford", state: "VA" },
  { city: "Staunton", state: "VA" },
  { city: "Waynesboro", state: "VA" },
  // Washington
  { city: "Seattle", state: "WA" },
  { city: "Spokane", state: "WA" },
  { city: "Tacoma", state: "WA" },
  { city: "Vancouver", state: "WA" },
  { city: "Bellevue", state: "WA" },
  { city: "Kent", state: "WA" },
  { city: "Everett", state: "WA" },
  { city: "Renton", state: "WA" },
  { city: "Kirkland", state: "WA" },
  { city: "Redmond", state: "WA" },
  { city: "Bellingham", state: "WA" },
  { city: "Federal Way", state: "WA" },
  { city: "Spokane Valley", state: "WA" },
  { city: "Marysville", state: "WA" },
  { city: "Kennewick", state: "WA" },
  { city: "Richland", state: "WA" },
  { city: "Pasco", state: "WA" },
  { city: "Yakima", state: "WA" },
  { city: "Sammamish", state: "WA" },
  { city: "Bothell", state: "WA" },
  { city: "Shoreline", state: "WA" },
  { city: "Burien", state: "WA" },
  { city: "Des Moines", state: "WA" },
  { city: "SeaTac", state: "WA" },
  { city: "Auburn", state: "WA" },
  { city: "Puyallup", state: "WA" },
  { city: "Lakewood", state: "WA" },
  { city: "Olympia", state: "WA" },
  { city: "Lacey", state: "WA" },
  { city: "Tumwater", state: "WA" },
  { city: "Bremerton", state: "WA" },
  { city: "Poulsbo", state: "WA" },
  { city: "Bainbridge Island", state: "WA" },
  { city: "Mercer Island", state: "WA" },
  { city: "Issaquah", state: "WA" },
  { city: "North Bend", state: "WA" },
  { city: "Snoqualmie", state: "WA" },
  { city: "Woodinville", state: "WA" },
  { city: "Mill Creek", state: "WA" },
  { city: "Lynnwood", state: "WA" },
  { city: "Edmonds", state: "WA" },
  { city: "Mountlake Terrace", state: "WA" },
  { city: "Lake Stevens", state: "WA" },
  { city: "Monroe", state: "WA" },
  { city: "Wenatchee", state: "WA" },
  { city: "Leavenworth", state: "WA" },
  { city: "Walla Walla", state: "WA" },
  { city: "Mount Vernon", state: "WA" },
  { city: "Oak Harbor", state: "WA" },
  { city: "Anacortes", state: "WA" },
  { city: "Port Townsend", state: "WA" },
  { city: "Port Angeles", state: "WA" },
  { city: "Sequim", state: "WA" },
  // West Virginia
  { city: "Charleston", state: "WV" },
  { city: "Huntington", state: "WV" },
  { city: "Parkersburg", state: "WV" },
  { city: "Morgantown", state: "WV" },
  { city: "Wheeling", state: "WV" },
  // Wisconsin
  { city: "Milwaukee", state: "WI" },
  { city: "Madison", state: "WI" },
  { city: "Green Bay", state: "WI" },
  { city: "Kenosha", state: "WI" },
  { city: "Racine", state: "WI" },
  { city: "Appleton", state: "WI" },
  { city: "Waukesha", state: "WI" },
  { city: "Eau Claire", state: "WI" },
  { city: "Oshkosh", state: "WI" },
  { city: "Janesville", state: "WI" },
  { city: "West Allis", state: "WI" },
  { city: "La Crosse", state: "WI" },
  { city: "Sheboygan", state: "WI" },
  { city: "Wauwatosa", state: "WI" },
  { city: "Brookfield", state: "WI" },
  { city: "Menomonee Falls", state: "WI" },
  { city: "New Berlin", state: "WI" },
  { city: "Greenfield", state: "WI" },
  { city: "Oak Creek", state: "WI" },
  { city: "Glendale", state: "WI" },
  { city: "Shorewood", state: "WI" },
  { city: "Whitefish Bay", state: "WI" },
  { city: "River Falls", state: "WI" },
  { city: "Fond du Lac", state: "WI" },
  { city: "Manitowoc", state: "WI" },
  { city: "Wausau", state: "WI" },
  { city: "Stevens Point", state: "WI" },
  { city: "Wisconsin Rapids", state: "WI" },
  { city: "Superior", state: "WI" },
  // Wyoming
  { city: "Cheyenne", state: "WY" },
  { city: "Casper", state: "WY" },
  { city: "Jackson", state: "WY" },
  { city: "Jackson Hole", state: "WY" },
  { city: "Laramie", state: "WY" },
  { city: "Gillette", state: "WY" },
  { city: "Rock Springs", state: "WY" },
  { city: "Teton Village", state: "WY" },
  // Canada
  // Alberta
  { city: "Calgary", state: "AB" },
  { city: "Edmonton", state: "AB" },
  { city: "Red Deer", state: "AB" },
  { city: "Lethbridge", state: "AB" },
  { city: "St. Albert", state: "AB" },
  // British Columbia
  { city: "Vancouver", state: "BC" },
  { city: "Victoria", state: "BC" },
  { city: "Surrey", state: "BC" },
  { city: "Burnaby", state: "BC" },
  { city: "Richmond", state: "BC" },
  { city: "Kelowna", state: "BC" },
  { city: "Abbotsford", state: "BC" },
  // Manitoba
  { city: "Winnipeg", state: "MB" },
  { city: "Brandon", state: "MB" },
  // New Brunswick
  { city: "Moncton", state: "NB" },
  { city: "Saint John", state: "NB" },
  { city: "Fredericton", state: "NB" },
  // Newfoundland and Labrador
  { city: "St. John's", state: "NL" },
  { city: "Corner Brook", state: "NL" },
  { city: "Gander", state: "NL" },
  // Northwest Territories
  { city: "Yellowknife", state: "NT" },
  { city: "Hay River", state: "NT" },
  // Nova Scotia
  { city: "Halifax", state: "NS" },
  { city: "Cape Breton", state: "NS" },
  // Nunavut
  { city: "Iqaluit", state: "NU" },
  // Ontario
  { city: "Toronto", state: "ON" },
  { city: "Ottawa", state: "ON" },
  { city: "Mississauga", state: "ON" },
  { city: "Brampton", state: "ON" },
  { city: "Hamilton", state: "ON" },
  { city: "London", state: "ON" },
  { city: "Markham", state: "ON" },
  { city: "Vaughan", state: "ON" },
  { city: "Kitchener", state: "ON" },
  { city: "Windsor", state: "ON" },
  { city: "Oshawa", state: "ON" },
  { city: "Thunder Bay", state: "ON" },
  { city: "Barrie", state: "ON" },
  // Prince Edward Island
  { city: "Charlottetown", state: "PE" },
  { city: "Summerside", state: "PE" },
  // Quebec
  { city: "Montreal", state: "QC" },
  { city: "Quebec City", state: "QC" },
  { city: "Laval", state: "QC" },
  { city: "Gatineau", state: "QC" },
  { city: "Longueuil", state: "QC" },
  { city: "Sherbrooke", state: "QC" },
  { city: "Saguenay", state: "QC" },
  { city: "Trois-Rivières", state: "QC" },
  // Saskatchewan
  { city: "Saskatoon", state: "SK" },
  { city: "Regina", state: "SK" },
  { city: "Prince Albert", state: "SK" },
  // Yukon
  { city: "Whitehorse", state: "YT" },
]
