export const US_CITIES: { city: string; state: string }[] = [
  // Alabama
  { city: "Birmingham", state: "AL" },
  { city: "Montgomery", state: "AL" },
  { city: "Huntsville", state: "AL" },
  { city: "Mobile", state: "AL" },
  { city: "Tuscaloosa", state: "AL" },
  // Alaska
  { city: "Anchorage", state: "AK" },
  { city: "Fairbanks", state: "AK" },
  { city: "Juneau", state: "AK" },
  // Arizona
  { city: "Phoenix", state: "AZ" },
  { city: "Tucson", state: "AZ" },
  { city: "Mesa", state: "AZ" },
  { city: "Chandler", state: "AZ" },
  { city: "Scottsdale", state: "AZ" },
  { city: "Gilbert", state: "AZ" },
  { city: "Tempe", state: "AZ" },
  { city: "Glendale", state: "AZ" },
  { city: "Peoria", state: "AZ" },
  { city: "Surprise", state: "AZ" },
  { city: "Sedona", state: "AZ" },
  { city: "Flagstaff", state: "AZ" },
  // Arkansas
  { city: "Little Rock", state: "AR" },
  { city: "Fort Smith", state: "AR" },
  { city: "Fayetteville", state: "AR" },
  { city: "Springdale", state: "AR" },
  // California
  { city: "Los Angeles", state: "CA" },
  { city: "San Diego", state: "CA" },
  { city: "San Jose", state: "CA" },
  { city: "San Francisco", state: "CA" },
  { city: "Fresno", state: "CA" },
  { city: "Sacramento", state: "CA" },
  { city: "Long Beach", state: "CA" },
  { city: "Oakland", state: "CA" },
  { city: "Bakersfield", state: "CA" },
  { city: "Anaheim", state: "CA" },
  { city: "Santa Ana", state: "CA" },
  { city: "Riverside", state: "CA" },
  { city: "Stockton", state: "CA" },
  { city: "Irvine", state: "CA" },
  { city: "Chula Vista", state: "CA" },
  { city: "Fremont", state: "CA" },
  { city: "San Bernardino", state: "CA" },
  { city: "Modesto", state: "CA" },
  { city: "Fontana", state: "CA" },
  { city: "Moreno Valley", state: "CA" },
  { city: "Glendale", state: "CA" },
  { city: "Huntington Beach", state: "CA" },
  { city: "Santa Clarita", state: "CA" },
  { city: "Garden Grove", state: "CA" },
  { city: "Oceanside", state: "CA" },
  { city: "Rancho Cucamonga", state: "CA" },
  { city: "Santa Rosa", state: "CA" },
  { city: "Ontario", state: "CA" },
  { city: "Corona", state: "CA" },
  { city: "Elk Grove", state: "CA" },
  { city: "Lancaster", state: "CA" },
  { city: "Palmdale", state: "CA" },
  { city: "Salinas", state: "CA" },
  { city: "Pomona", state: "CA" },
  { city: "Torrance", state: "CA" },
  { city: "Escondido", state: "CA" },
  { city: "Sunnyvale", state: "CA" },
  { city: "Pasadena", state: "CA" },
  { city: "Orange", state: "CA" },
  { city: "Fullerton", state: "CA" },
  { city: "Hayward", state: "CA" },
  { city: "Visalia", state: "CA" },
  { city: "Concord", state: "CA" },
  { city: "Roseville", state: "CA" },
  { city: "Santa Clara", state: "CA" },
  { city: "Thousand Oaks", state: "CA" },
  { city: "Simi Valley", state: "CA" },
  { city: "Vallejo", state: "CA" },
  { city: "Victorville", state: "CA" },
  { city: "El Monte", state: "CA" },
  { city: "Berkeley", state: "CA" },
  { city: "Downey", state: "CA" },
  { city: "Costa Mesa", state: "CA" },
  { city: "Inglewood", state: "CA" },
  { city: "Ventura", state: "CA" },
  { city: "West Covina", state: "CA" },
  { city: "Norwalk", state: "CA" },
  { city: "Burbank", state: "CA" },
  { city: "Antioch", state: "CA" },
  { city: "Santa Monica", state: "CA" },
  { city: "Beverly Hills", state: "CA" },
  { city: "Malibu", state: "CA" },
  { city: "Palm Springs", state: "CA" },
  { city: "Newport Beach", state: "CA" },
  { city: "Laguna Beach", state: "CA" },
  { city: "San Luis Obispo", state: "CA" },
  { city: "Santa Barbara", state: "CA" },
  { city: "Napa", state: "CA" },
  { city: "Palo Alto", state: "CA" },
  { city: "Mountain View", state: "CA" },
  { city: "Redwood City", state: "CA" },
  { city: "San Mateo", state: "CA" },
  { city: "Daly City", state: "CA" },
  { city: "South San Francisco", state: "CA" },
  { city: "San Leandro", state: "CA" },
  { city: "Richmond", state: "CA" },
  { city: "Petaluma", state: "CA" },
  { city: "Hollywood", state: "CA" },
  // Colorado
  { city: "Denver", state: "CO" },
  { city: "Colorado Springs", state: "CO" },
  { city: "Aurora", state: "CO" },
  { city: "Fort Collins", state: "CO" },
  { city: "Lakewood", state: "CO" },
  { city: "Thornton", state: "CO" },
  { city: "Arvada", state: "CO" },
  { city: "Westminster", state: "CO" },
  { city: "Pueblo", state: "CO" },
  { city: "Boulder", state: "CO" },
  { city: "Aspen", state: "CO" },
  { city: "Vail", state: "CO" },
  // Connecticut
  { city: "Bridgeport", state: "CT" },
  { city: "New Haven", state: "CT" },
  { city: "Stamford", state: "CT" },
  { city: "Hartford", state: "CT" },
  { city: "Waterbury", state: "CT" },
  { city: "Greenwich", state: "CT" },
  { city: "Norwalk", state: "CT" },
  // Delaware
  { city: "Wilmington", state: "DE" },
  { city: "Dover", state: "DE" },
  // Florida
  { city: "Jacksonville", state: "FL" },
  { city: "Miami", state: "FL" },
  { city: "Tampa", state: "FL" },
  { city: "Orlando", state: "FL" },
  { city: "St. Petersburg", state: "FL" },
  { city: "Hialeah", state: "FL" },
  { city: "Port St. Lucie", state: "FL" },
  { city: "Cape Coral", state: "FL" },
  { city: "Tallahassee", state: "FL" },
  { city: "Fort Lauderdale", state: "FL" },
  { city: "Pembroke Pines", state: "FL" },
  { city: "Hollywood", state: "FL" },
  { city: "Miramar", state: "FL" },
  { city: "Gainesville", state: "FL" },
  { city: "Coral Springs", state: "FL" },
  { city: "Miami Gardens", state: "FL" },
  { city: "Clearwater", state: "FL" },
  { city: "Palm Bay", state: "FL" },
  { city: "Pompano Beach", state: "FL" },
  { city: "West Palm Beach", state: "FL" },
  { city: "Lakeland", state: "FL" },
  { city: "Davie", state: "FL" },
  { city: "Miami Beach", state: "FL" },
  { city: "Sunrise", state: "FL" },
  { city: "Plantation", state: "FL" },
  { city: "Boca Raton", state: "FL" },
  { city: "Deltona", state: "FL" },
  { city: "Largo", state: "FL" },
  { city: "Deerfield Beach", state: "FL" },
  { city: "Palm Coast", state: "FL" },
  { city: "Melbourne", state: "FL" },
  { city: "Boynton Beach", state: "FL" },
  { city: "Lauderhill", state: "FL" },
  { city: "Fort Myers", state: "FL" },
  { city: "Sarasota", state: "FL" },
  { city: "Daytona Beach", state: "FL" },
  { city: "Naples", state: "FL" },
  { city: "Key West", state: "FL" },
  { city: "Kissimmee", state: "FL" },
  { city: "Sanford", state: "FL" },
  { city: "Ocala", state: "FL" },
  { city: "Pensacola", state: "FL" },
  { city: "Aventura", state: "FL" },
  { city: "Doral", state: "FL" },
  { city: "Coral Gables", state: "FL" },
  { city: "Hallandale Beach", state: "FL" },
  { city: "Homestead", state: "FL" },
  { city: "Delray Beach", state: "FL" },
  { city: "Lake Worth", state: "FL" },
  { city: "Margate", state: "FL" },
  { city: "Coconut Creek", state: "FL" },
  { city: "North Miami", state: "FL" },
  { city: "Weston", state: "FL" },
  { city: "Tamarac", state: "FL" },
  { city: "Tallahassee", state: "FL" },
  { city: "St. Augustine", state: "FL" },
  { city: "Bradenton", state: "FL" },
  // Georgia
  { city: "Atlanta", state: "GA" },
  { city: "Columbus", state: "GA" },
  { city: "Augusta", state: "GA" },
  { city: "Macon", state: "GA" },
  { city: "Savannah", state: "GA" },
  { city: "Athens", state: "GA" },
  { city: "Sandy Springs", state: "GA" },
  { city: "Roswell", state: "GA" },
  { city: "Alpharetta", state: "GA" },
  { city: "Marietta", state: "GA" },
  // Hawaii
  { city: "Honolulu", state: "HI" },
  { city: "Hilo", state: "HI" },
  { city: "Kailua", state: "HI" },
  { city: "Lahaina", state: "HI" },
  // Idaho
  { city: "Boise", state: "ID" },
  { city: "Meridian", state: "ID" },
  { city: "Nampa", state: "ID" },
  { city: "Idaho Falls", state: "ID" },
  { city: "Coeur d'Alene", state: "ID" },
  // Illinois
  { city: "Chicago", state: "IL" },
  { city: "Aurora", state: "IL" },
  { city: "Joliet", state: "IL" },
  { city: "Naperville", state: "IL" },
  { city: "Rockford", state: "IL" },
  { city: "Springfield", state: "IL" },
  { city: "Elgin", state: "IL" },
  { city: "Peoria", state: "IL" },
  { city: "Champaign", state: "IL" },
  { city: "Waukegan", state: "IL" },
  { city: "Evanston", state: "IL" },
  { city: "Oak Park", state: "IL" },
  { city: "Schaumburg", state: "IL" },
  // Indiana
  { city: "Indianapolis", state: "IN" },
  { city: "Fort Wayne", state: "IN" },
  { city: "Evansville", state: "IN" },
  { city: "South Bend", state: "IN" },
  { city: "Carmel", state: "IN" },
  { city: "Bloomington", state: "IN" },
  // Iowa
  { city: "Des Moines", state: "IA" },
  { city: "Cedar Rapids", state: "IA" },
  { city: "Davenport", state: "IA" },
  { city: "Sioux City", state: "IA" },
  // Kansas
  { city: "Wichita", state: "KS" },
  { city: "Overland Park", state: "KS" },
  { city: "Kansas City", state: "KS" },
  { city: "Topeka", state: "KS" },
  { city: "Olathe", state: "KS" },
  // Kentucky
  { city: "Louisville", state: "KY" },
  { city: "Lexington", state: "KY" },
  { city: "Bowling Green", state: "KY" },
  { city: "Owensboro", state: "KY" },
  // Louisiana
  { city: "New Orleans", state: "LA" },
  { city: "Baton Rouge", state: "LA" },
  { city: "Shreveport", state: "LA" },
  { city: "Metairie", state: "LA" },
  { city: "Lafayette", state: "LA" },
  // Maine
  { city: "Portland", state: "ME" },
  { city: "Augusta", state: "ME" },
  { city: "Bangor", state: "ME" },
  // Maryland
  { city: "Baltimore", state: "MD" },
  { city: "Frederick", state: "MD" },
  { city: "Rockville", state: "MD" },
  { city: "Gaithersburg", state: "MD" },
  { city: "Bowie", state: "MD" },
  { city: "Annapolis", state: "MD" },
  { city: "Bethesda", state: "MD" },
  { city: "Silver Spring", state: "MD" },
  // Massachusetts
  { city: "Boston", state: "MA" },
  { city: "Worcester", state: "MA" },
  { city: "Springfield", state: "MA" },
  { city: "Lowell", state: "MA" },
  { city: "Cambridge", state: "MA" },
  { city: "New Bedford", state: "MA" },
  { city: "Brockton", state: "MA" },
  { city: "Quincy", state: "MA" },
  { city: "Lynn", state: "MA" },
  { city: "Fall River", state: "MA" },
  { city: "Newton", state: "MA" },
  { city: "Somerville", state: "MA" },
  // Michigan
  { city: "Detroit", state: "MI" },
  { city: "Grand Rapids", state: "MI" },
  { city: "Warren", state: "MI" },
  { city: "Sterling Heights", state: "MI" },
  { city: "Ann Arbor", state: "MI" },
  { city: "Lansing", state: "MI" },
  { city: "Flint", state: "MI" },
  { city: "Dearborn", state: "MI" },
  { city: "Livonia", state: "MI" },
  { city: "Troy", state: "MI" },
  { city: "Kalamazoo", state: "MI" },
  { city: "Traverse City", state: "MI" },
  // Minnesota
  { city: "Minneapolis", state: "MN" },
  { city: "St. Paul", state: "MN" },
  { city: "Rochester", state: "MN" },
  { city: "Duluth", state: "MN" },
  { city: "Bloomington", state: "MN" },
  { city: "Brooklyn Park", state: "MN" },
  { city: "Plymouth", state: "MN" },
  { city: "Maple Grove", state: "MN" },
  // Mississippi
  { city: "Jackson", state: "MS" },
  { city: "Gulfport", state: "MS" },
  { city: "Biloxi", state: "MS" },
  // Missouri
  { city: "Kansas City", state: "MO" },
  { city: "St. Louis", state: "MO" },
  { city: "Springfield", state: "MO" },
  { city: "Columbia", state: "MO" },
  { city: "Independence", state: "MO" },
  // Montana
  { city: "Billings", state: "MT" },
  { city: "Missoula", state: "MT" },
  { city: "Great Falls", state: "MT" },
  { city: "Bozeman", state: "MT" },
  // Nebraska
  { city: "Omaha", state: "NE" },
  { city: "Lincoln", state: "NE" },
  { city: "Bellevue", state: "NE" },
  // Nevada
  { city: "Las Vegas", state: "NV" },
  { city: "Henderson", state: "NV" },
  { city: "Reno", state: "NV" },
  { city: "North Las Vegas", state: "NV" },
  { city: "Sparks", state: "NV" },
  // New Hampshire
  { city: "Manchester", state: "NH" },
  { city: "Nashua", state: "NH" },
  { city: "Concord", state: "NH" },
  // New Jersey
  { city: "Newark", state: "NJ" },
  { city: "Jersey City", state: "NJ" },
  { city: "Paterson", state: "NJ" },
  { city: "Elizabeth", state: "NJ" },
  { city: "Edison", state: "NJ" },
  { city: "Woodbridge", state: "NJ" },
  { city: "Lakewood", state: "NJ" },
  { city: "Toms River", state: "NJ" },
  { city: "Hamilton", state: "NJ" },
  { city: "Trenton", state: "NJ" },
  { city: "Clifton", state: "NJ" },
  { city: "Camden", state: "NJ" },
  { city: "Hoboken", state: "NJ" },
  { city: "Princeton", state: "NJ" },
  { city: "Atlantic City", state: "NJ" },
  { city: "Cherry Hill", state: "NJ" },
  // New Mexico
  { city: "Albuquerque", state: "NM" },
  { city: "Las Cruces", state: "NM" },
  { city: "Rio Rancho", state: "NM" },
  { city: "Santa Fe", state: "NM" },
  // New York
  { city: "New York City", state: "NY" },
  { city: "Manhattan", state: "NY" },
  { city: "Brooklyn", state: "NY" },
  { city: "Queens", state: "NY" },
  { city: "Bronx", state: "NY" },
  { city: "Staten Island", state: "NY" },
  { city: "Buffalo", state: "NY" },
  { city: "Rochester", state: "NY" },
  { city: "Yonkers", state: "NY" },
  { city: "Syracuse", state: "NY" },
  { city: "Albany", state: "NY" },
  { city: "New Rochelle", state: "NY" },
  { city: "Mount Vernon", state: "NY" },
  { city: "Schenectady", state: "NY" },
  { city: "Utica", state: "NY" },
  { city: "White Plains", state: "NY" },
  { city: "Hempstead", state: "NY" },
  { city: "Troy", state: "NY" },
  { city: "Niagara Falls", state: "NY" },
  { city: "Ithaca", state: "NY" },
  { city: "Long Island City", state: "NY" },
  { city: "Flushing", state: "NY" },
  { city: "Astoria", state: "NY" },
  { city: "Harlem", state: "NY" },
  { city: "Southampton", state: "NY" },
  { city: "Hamptons", state: "NY" },
  // North Carolina
  { city: "Charlotte", state: "NC" },
  { city: "Raleigh", state: "NC" },
  { city: "Greensboro", state: "NC" },
  { city: "Durham", state: "NC" },
  { city: "Winston-Salem", state: "NC" },
  { city: "Fayetteville", state: "NC" },
  { city: "Cary", state: "NC" },
  { city: "Wilmington", state: "NC" },
  { city: "High Point", state: "NC" },
  { city: "Chapel Hill", state: "NC" },
  { city: "Asheville", state: "NC" },
  // North Dakota
  { city: "Fargo", state: "ND" },
  { city: "Bismarck", state: "ND" },
  { city: "Grand Forks", state: "ND" },
  // Ohio
  { city: "Columbus", state: "OH" },
  { city: "Cleveland", state: "OH" },
  { city: "Cincinnati", state: "OH" },
  { city: "Toledo", state: "OH" },
  { city: "Akron", state: "OH" },
  { city: "Dayton", state: "OH" },
  { city: "Parma", state: "OH" },
  { city: "Canton", state: "OH" },
  { city: "Youngstown", state: "OH" },
  // Oklahoma
  { city: "Oklahoma City", state: "OK" },
  { city: "Tulsa", state: "OK" },
  { city: "Norman", state: "OK" },
  { city: "Broken Arrow", state: "OK" },
  // Oregon
  { city: "Portland", state: "OR" },
  { city: "Salem", state: "OR" },
  { city: "Eugene", state: "OR" },
  { city: "Gresham", state: "OR" },
  { city: "Hillsboro", state: "OR" },
  { city: "Beaverton", state: "OR" },
  // Pennsylvania
  { city: "Philadelphia", state: "PA" },
  { city: "Pittsburgh", state: "PA" },
  { city: "Allentown", state: "PA" },
  { city: "Erie", state: "PA" },
  { city: "Reading", state: "PA" },
  { city: "Scranton", state: "PA" },
  { city: "Bethlehem", state: "PA" },
  { city: "Lancaster", state: "PA" },
  { city: "Harrisburg", state: "PA" },
  { city: "York", state: "PA" },
  // Rhode Island
  { city: "Providence", state: "RI" },
  { city: "Warwick", state: "RI" },
  { city: "Cranston", state: "RI" },
  // South Carolina
  { city: "Columbia", state: "SC" },
  { city: "Charleston", state: "SC" },
  { city: "North Charleston", state: "SC" },
  { city: "Mount Pleasant", state: "SC" },
  { city: "Greenville", state: "SC" },
  { city: "Myrtle Beach", state: "SC" },
  { city: "Hilton Head", state: "SC" },
  // South Dakota
  { city: "Sioux Falls", state: "SD" },
  { city: "Rapid City", state: "SD" },
  // Tennessee
  { city: "Memphis", state: "TN" },
  { city: "Nashville", state: "TN" },
  { city: "Knoxville", state: "TN" },
  { city: "Chattanooga", state: "TN" },
  { city: "Clarksville", state: "TN" },
  { city: "Murfreesboro", state: "TN" },
  // Texas
  { city: "Houston", state: "TX" },
  { city: "San Antonio", state: "TX" },
  { city: "Dallas", state: "TX" },
  { city: "Austin", state: "TX" },
  { city: "Fort Worth", state: "TX" },
  { city: "El Paso", state: "TX" },
  { city: "Arlington", state: "TX" },
  { city: "Corpus Christi", state: "TX" },
  { city: "Plano", state: "TX" },
  { city: "Laredo", state: "TX" },
  { city: "Lubbock", state: "TX" },
  { city: "Garland", state: "TX" },
  { city: "Irving", state: "TX" },
  { city: "Amarillo", state: "TX" },
  { city: "Grand Prairie", state: "TX" },
  { city: "Brownsville", state: "TX" },
  { city: "Pasadena", state: "TX" },
  { city: "McKinney", state: "TX" },
  { city: "Killeen", state: "TX" },
  { city: "Frisco", state: "TX" },
  { city: "McAllen", state: "TX" },
  { city: "Mesquite", state: "TX" },
  { city: "Midland", state: "TX" },
  { city: "Denton", state: "TX" },
  { city: "Waco", state: "TX" },
  { city: "Carrollton", state: "TX" },
  { city: "Round Rock", state: "TX" },
  { city: "Abilene", state: "TX" },
  { city: "Beaumont", state: "TX" },
  { city: "Odessa", state: "TX" },
  { city: "Richardson", state: "TX" },
  { city: "Pearland", state: "TX" },
  { city: "San Angelo", state: "TX" },
  { city: "Allen", state: "TX" },
  { city: "Sugar Land", state: "TX" },
  { city: "League City", state: "TX" },
  { city: "The Woodlands", state: "TX" },
  { city: "Tyler", state: "TX" },
  { city: "Galveston", state: "TX" },
  // Utah
  { city: "Salt Lake City", state: "UT" },
  { city: "West Valley City", state: "UT" },
  { city: "Provo", state: "UT" },
  { city: "West Jordan", state: "UT" },
  { city: "Orem", state: "UT" },
  { city: "Sandy", state: "UT" },
  { city: "St. George", state: "UT" },
  { city: "Park City", state: "UT" },
  // Vermont
  { city: "Burlington", state: "VT" },
  { city: "Montpelier", state: "VT" },
  // Virginia
  { city: "Virginia Beach", state: "VA" },
  { city: "Norfolk", state: "VA" },
  { city: "Chesapeake", state: "VA" },
  { city: "Richmond", state: "VA" },
  { city: "Newport News", state: "VA" },
  { city: "Alexandria", state: "VA" },
  { city: "Hampton", state: "VA" },
  { city: "Roanoke", state: "VA" },
  { city: "Arlington", state: "VA" },
  { city: "McLean", state: "VA" },
  { city: "Tysons", state: "VA" },
  // Washington
  { city: "Seattle", state: "WA" },
  { city: "Spokane", state: "WA" },
  { city: "Tacoma", state: "WA" },
  { city: "Vancouver", state: "WA" },
  { city: "Bellevue", state: "WA" },
  { city: "Kent", state: "WA" },
  { city: "Everett", state: "WA" },
  { city: "Renton", state: "WA" },
  { city: "Kirkland", state: "WA" },
  { city: "Redmond", state: "WA" },
  { city: "Bellingham", state: "WA" },
  // Washington DC
  { city: "Washington", state: "DC" },
  // West Virginia
  { city: "Charleston", state: "WV" },
  { city: "Huntington", state: "WV" },
  // Wisconsin
  { city: "Milwaukee", state: "WI" },
  { city: "Madison", state: "WI" },
  { city: "Green Bay", state: "WI" },
  { city: "Kenosha", state: "WI" },
  { city: "Racine", state: "WI" },
  // Wyoming
  { city: "Cheyenne", state: "WY" },
  { city: "Casper", state: "WY" },
  { city: "Jackson", state: "WY" },
]
